CREATE OR REPLACE VIEW US_GDMON.ALL_TAB_COMMENTS AS
SELECT U.USER_NAME OWNER
     , T.TABLE_NAME
     , DECODE(T.TABLE_TYPE,'T','TABLE','V','VIEW') TABLE_TYPE
     , M.COMMENTS
  FROM SYSTEM_.SYS_USERS_ U
       INNER JOIN SYSTEM_.SYS_TABLES_ T
               ON U.USER_ID = T.USER_ID
              AND T.TABLE_TYPE IN ( 'T', 'V' )
       LEFT OUTER JOIN SYSTEM_.SYS_COMMENTS_ M
               ON M.USER_NAME = U.USER_NAME
              AND M.TABLE_NAME = T.TABLE_NAME
              AND M.COLUMN_NAME IS NULL
 WHERE 1=1
   AND U.USER_NAME NOT IN ( 'SYS', 'SYSTEM_' ) AND U.USER_NAME NOT LIKE '%MNG' AND U.USER_NAME NOT LIKE '%APP' AND U.USER_NAME NOT LIKE '%SEL'
   --AND U.USER_NAME = USER_NAME()
;

GRANT SELECT ON US_GDMON.ALL_TAB_COMMENTS TO PUBLIC;
