CREATE OR REPLACE VIEW US_GDMON.ALL_TAB_PRIVS AS
SELECT U1.USER_NAME GRANTOR
     , U2.USER_NAME GRANTEE
     , U3.USER_NAME TABLE_SCHEMA
     , T.TABLE_NAME
     , P.PRIV_NAME PRIVILEGE
     , DECODE(GO.OBJ_TYPE, 'T', 'TABLE', 'S', 'SEQUENCE', 'V', 'VIEW', 'P', 'PROCEDURE', 'UNKNOWN') OBJECT_TYPE
     , DECODE(GO.WITH_GRANT_OPTION, 0, 'NO', 'YES') GRANTABLE
     , T.CREATED
     , T.LAST_DDL_TIME
     --, GO.*
  FROM SYSTEM_.SYS_GRANT_OBJECT_ GO
       INNER JOIN SYSTEM_.SYS_USERS_ U1 ON U1.USER_ID = GO.GRANTOR_ID
       INNER JOIN SYSTEM_.SYS_USERS_ U2 ON U2.USER_ID = GO.GRANTEE_ID
       INNER JOIN SYSTEM_.SYS_USERS_ U3 ON U3.USER_ID = GO.USER_ID
       INNER JOIN SYSTEM_.SYS_TABLES_ T ON T.TABLE_ID = GO.OBJ_ID
       INNER JOIN SYSTEM_.SYS_PRIVILEGES_ P ON P.PRIV_ID = GO.PRIV_ID
 WHERE 1=1
   --AND GO.OBJ_TYPE NOT IN ( 'T', 'S' )
   --AND GO.WITH_GRANT_OPTION <> 0
 UNION ALL
SELECT U1.USER_NAME GRANTOR
     , U2.USER_NAME GRANTEE
     , U3.USER_NAME TABLE_SCHEMA
     , T.PROC_NAME
     , P.PRIV_NAME PRIVILEGE
     , DECODE(GO.OBJ_TYPE, 'T', 'TABLE', 'S', 'SEQUENCE', 'V', 'VIEW', 'P', 'PROCEDURE', 'UNKNOWN') OBJECT_TYPE
     , DECODE(GO.WITH_GRANT_OPTION, 0, 'NO', 'YES') GRANTABLE
     , T.CREATED
     , T.LAST_DDL_TIME
     --, GO.*
  FROM SYSTEM_.SYS_GRANT_OBJECT_ GO
       INNER JOIN SYSTEM_.SYS_USERS_ U1 ON U1.USER_ID = GO.GRANTOR_ID
       INNER JOIN SYSTEM_.SYS_USERS_ U2 ON U2.USER_ID = GO.GRANTEE_ID
       INNER JOIN SYSTEM_.SYS_USERS_ U3 ON U3.USER_ID = GO.USER_ID
       INNER JOIN SYSTEM_.SYS_PROCEDURES_ T ON T.PROC_OID = GO.OBJ_ID
       INNER JOIN SYSTEM_.SYS_PRIVILEGES_ P ON P.PRIV_ID = GO.PRIV_ID
 WHERE 1=1
   --AND GO.OBJ_TYPE NOT IN ( 'T', 'S', 'P')
   --AND GO.WITH_GRANT_OPTION <> 0
;

GRANT SELECT ON US_GDMON.ALL_TAB_PRIVS TO PUBLIC;
