CREATE OR REPLACE VIEW US_GDMON.GD_DBA_TAB_COLUMNS AS
SELECT U.USER_NAME OWNER
     , T.TABLE_NAME
     , C.COLUMN_NAME
     , SF_COL_TYPE( C.DATA_TYPE, C.PRECISION, C.SCALE ) DATA_TYPE
     , DECODE(C.IS_NULLABLE,'T','Y','N') NULLABLE
     , C.DEFAULT_VAL DATA_DEFAULT
     , C.COLUMN_ORDER
     , M.COMMENTS
     --, COUNT(*) CNT
  FROM SYSTEM_.SYS_USERS_ U
       INNER JOIN SYSTEM_.SYS_TABLES_ T
               ON U.USER_ID = T.USER_ID
              AND T.TABLE_TYPE = 'T'
       INNER JOIN SYSTEM_.SYS_COLUMNS_ C
               ON T.TABLE_ID = C.TABLE_ID
       LEFT OUTER JOIN SYSTEM_.SYS_COMMENTS_ M
               ON M.USER_NAME = U.USER_NAME
              AND M.TABLE_NAME = T.TABLE_NAME
              AND M.COLUMN_NAME = C.COLUMN_NAME
 WHERE 1=1
   --AND U.USER_NAME NOT IN ( 'SYS', 'SYSTEM_' ) AND U.USER_NAME NOT LIKE '%MNG' AND U.USER_NAME NOT LIKE '%APP'
   --AND U.USER_NAME = USER_NAME()
 --GROUP BY C.COLUMN_NAME, C.DATA_TYPE, C.PRECISION, C.SCALE
;
