CREATE OR REPLACE VIEW GDMON_OBJECTS AS
SELECT U.USER_NAME OWNER
     , T.TABLE_NAME OBJECT_NAME
     , DECODE( TABLE_TYPE,'T','TABLE','V','VIEW','S','SEQUENCE','UNKNOWN-'||TABLE_TYPE ) OBJECT_TYPE
     , CAST( 'VALID' AS VARCHAR(10)) STATUS
     , T.CREATED, T.LAST_DDL_TIME
  FROM SYSTEM_.SYS_TABLES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.INDEX_NAME
     , 'INDEX'    
     , 'VALID'
     , T.CREATED, T.LAST_DDL_TIME
  FROM SYSTEM_.SYS_INDICES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.PROC_NAME
     , DECODE(OBJECT_TYPE,0,'PROCEDURE',1,'FUNCTION',3,'TYPE','UNKNOWN-'||OBJECT_TYPE)
     , DECODE(STATUS,0,'VALID','INVALID')
     , T.CREATED, T.LAST_DDL_TIME
  FROM SYSTEM_.SYS_PROCEDURES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.TRIGGER_NAME
     , 'TRIGGER'    
     , DECODE(IS_ENABLE,1,'VALID','INVALID')
     , T.CREATED, T.LAST_DDL_TIME
  FROM SYSTEM_.SYS_TRIGGERS_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.SYNONYM_NAME
     , 'SYNONYM'    
     , 'VALID' -- [TODO] check target synonym
     , T.CREATED, T.LAST_DDL_TIME
  FROM SYSTEM_.SYS_SYNONYMS_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.SYNONYM_OWNER_ID
 WHERE 1=1
-- [TODO] Add 'FK' - SYSTEM_.SYS_CONSTRAINTS_
;

CREATE PUBLIC SYNONYM GDMON_OBJECTS FOR US_GDMON.GDMON_OBJECTS ;

