DECLARE
    V_C1 VARCHAR(100);

    CURSOR C1
    IS
    SELECT CAST( ROWNUM AS CHAR(100) ) NO FROM DUAL CONNECT BY LEVEL <= 10;
    --SELECT CAST( ROWNUM AS CHAR(100) ) NO FROM DUAL CONNECT BY LEVEL <= 100000;
BEGIN
    OPEN C1;

    LOOP
        FETCH C1 INTO V_C1 ;
        EXIT WHEN C1%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('['|| V_C1 || ']');
UPDATE OKT SET I1 = I1 LIMIT 1;
    --CLOSE C1;
        --ROLLBACK;
--UPDATE OKT SET I1 = I1 LIMIT 1;
        --COMMIT;
        COMMIT WORK RELEASE;
    END LOOP;

    CLOSE C1;
END;
/

