CREATE OR REPLACE FUNCTION IS_NUMBERCHK
(
  V_STR_NUMBER VARCHAR(13)
)
RETURN CHAR(1)
AS V_ISNUM NUMBER;
   V_ISCHK CHAR(1);
BEGIN
   V_ISNUM := TO_NUMBER(V_STR_NUMBER);

   IF LENGTH(V_ISNUM) <> 13 THEN
    V_ISCHK := 'F';
   ELSE
    V_ISCHK := 'T';
   END IF;

   RETURN V_ISCHK;

EXCEPTION
   WHEN OTHERS THEN
   RETURN 'F';
END;
/
