DROP TABLE GDR_SQLAREA;
CREATE TABLE GDR_SQLAREA
(
	SQL_ID					NUMBER
,	SQL_CACHE_TEXT_ID		VARCHAR(64)
--,	CHILD_NUMBER			NUMBER
--,	HASH_VALUE				NUMBER
,	PLAN_HASH_VALUE			NUMBER DEFAULT 0
,	FIRST_LOAD_TIME			DATE
,	LAST_ACTIVE_TIME		DATE
--,	PARSING_USER_ID			NUMBER
,	PARSING_SCHEMA_NAME		VARCHAR(64)
,	MODULE					VARCHAR(128)
--,	ACTION					VARCHAR(64)
--,	IS_SHAREABLE			VARCHAR(1)
,	CPU_TIME				NUMBER DEFAULT 0	-- EXECUTE_TIME (?) OR TOTAL_TIME - FETCH_TIME - WAIT_TIME
,	ELAPSED_TIME			NUMBER DEFAULT 0	-- TOTAL_TIME
,	PVO_TIME				NUMBER DEFAULT 0	-- PARSE_TIME + VALIDATE_TIME + OPTIMIZE_TIME + SOFT_PREPARE_TIME
--,	RUNTIME_MEM				NUMBER DEFAULT 0	-- USED_MEMORY But Always 0
,	FETCH_TIME				NUMBER DEFAULT 0
,	PARSE_CALLS				NUMBER DEFAULT 0	-- HOW ?
--,	ROWS_PROCESSED			NUMBER DEFAULT 0	-- PROCESS_ROW
,	ROWS_MODIFIED			NUMBER DEFAULT 0	-- PROCESS_ROW
,	COMMAND_TYPE			NUMBER 				-- 1: CREATE , 2: I, 3: S, 6: U, 7: D, 26: LOCK TABLE, 47: BEGIN, 170: CALL, 189: MERGE, ?:  MOVE,
,	FETCHES					NUMBER DEFAULT 0	-- FETCH_SUCCESS (?)
,	EXECUTIONS				NUMBER DEFAULT 0	-- EXECUTE_SUCCESS
--,	END_OF_FETCH_COUNT		NUMBER DEFAULT 0
--,	PX_SERVERS_EXECUTIONS	NUMBER DEFAULT 0
--,	APPLICATION_WAIT_TIME	NUMBER DEFAULT 0
--,	CONCURRENCY_WAIT_TIME	NUMBER DEFAULT 0
--,	CLUSTER_WAIT_TIME		NUMBER DEFAULT 0
--,	USER_IO_WAIT_TIME		NUMBER DEFAULT 0
,	WAIT_TIME				NUMBER DEFAULT 0	-- TODO: ms OR us (?)
,	DISK_READS				NUMBER DEFAULT 0	-- READ_PAGE + UNDO_READ_PAGE
--,	DIRECT_WRITES			NUMBER DEFAULT 0
,	BUFFER_GETS				NUMBER DEFAULT 0	-- GET_PAGE + UNDO_GET_PAGE
,	DISK_CREATES			NUMBER DEFAULT 0	-- CREATE_PAGE + UNDO_CREATE_PAGE
--,	PHYSICAL_READ_REQUESTS	NUMBER DEFAULT 0
--,	PHYSICAL_READ_BYTES		NUMBER DEFAULT 0
--,	PHYSICAL_WRITE_REQUESTS	NUMBER DEFAULT 0
--,	PHYSICAL_WRITE_BYTES	NUMBER DEFAULT 0
--,	SORTS					NUMBER DEFAULT 0
,	VERSION_COUNT			NUMBER DEFAULT 0
,	IS_FULLSCAN				NUMBER	-- DISK_CURSOR_FULL_SCAN + MEM_CURSOR_FULL_SCAN
,	EVENT					VARCHAR(128)	-- <> 'no wait event'
--,	OBJECT_STATUS			VARCHAR(14)
,	SQL_TEXT				VARCHAR(32000)
,	LAST_SAMPLE_CNT			NUMBER DEFAULT 1
,	LAST_SAMPLE_ID			NUMBER
,	LAST_SESSION_ID			NUMBER
,	LAST_STMT_ID			NUMBER
,	LAST_UPDATE_TIME		DATE DEFAULT SYSDATE
,	CREATED					DATE DEFAULT SYSDATE
)
--TABLESPACE VOL_TS
;

DROP INDEX IX_GDR_SQLAREA_NI01;
DROP INDEX IX_GDR_SQLAREA_NI02;
DROP INDEX IX_GDR_SQLAREA_NI03;

CREATE UNIQUE INDEX IX_GDR_SQLAREA_NI01 ON GDR_SQLAREA ( SQL_ID ) ;
CREATE INDEX IX_GDR_SQLAREA_NI02 ON GDR_SQLAREA ( SQL_CACHE_TEXT_ID ) ;
CREATE INDEX IX_GDR_SQLAREA_NI03 ON GDR_SQLAREA ( LAST_SAMPLE_ID ) ;


/*
*/
