CREATE OR REPLACE PROCEDURE GDR_SP_SAMPLE_DELTA
(
	A_SAMPLE_ID			IN	VARCHAR(64) DEFAULT NULL
)
is
	V_SQLCODE				VARCHAR(64);
	V_SQLERRM				VARCHAR(2047);

	V_SAMPLE_ID				VARCHAR(64);
	V_SAMPLE_TIME			DATE;
	V_SAMPLE_INTERVAL		NUMBER(15,6);
	V_PREV_SAMPLE_ID		VARCHAR(64);
	V_PREV_SAMPLE_TIME		DATE;

	V_STM					DATE;
	V_DTM					NUMBER(15,6);	-- MICROSECOND

BEGIN
	V_SQLCODE := 0;
	V_SQLERRM := ' ';
	V_STM := SYSDATE;
	V_DTM := 0;

SYSTEM_.PRINTLN(NULL);
V_STM := GDR_SF_CHECKTIME( V_STM, V_DTM ); SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ['||V_DTM||'] GDR_SP_SAMPLE_DELTA - START !!');

	IF A_SAMPLE_ID IS NULL THEN
    	SELECT MAX(SAMPLE_ID) INTO V_SAMPLE_ID FROM GDR_HIST_SAMPLESHOT ;
	ELSE
		V_SAMPLE_ID := A_SAMPLE_ID ;
	END IF;

	SELECT SAMPLE_INTERVAL INTO V_SAMPLE_INTERVAL FROM GDR_HIST_SAMPLESHOT WHERE SAMPLE_ID = V_SAMPLE_ID ;
	SELECT SAMPLE_ID INTO V_PREV_SAMPLE_ID FROM GDR_HIST_SAMPLESHOT WHERE SAMPLE_ID < V_SAMPLE_ID ORDER BY SAMPLE_ID DESC LIMIT 1;

	UPDATE GDR_TMP_SYSSTAT A
	   SET ( A.DELTA_VALUE, A.SEC_DELTA_VALUE ) = ( SELECT ( A.VALUE - X.VALUE ) , ( A.VALUE - X.VALUE )/V_SAMPLE_INTERVAL FROM GDR_TMP_SYSSTAT X WHERE X.SAMPLE_ID = V_PREV_SAMPLE_ID AND X.SEQNUM = A.SEQNUM )
	 WHERE 1=1
	   AND A.SAMPLE_ID = V_SAMPLE_ID
	   AND ( A_SAMPLE_ID IS NOT NULL OR A.DELTA_VALUE IS NULL )
    ;
V_STM := GDR_SF_CHECKTIME( V_STM, V_DTM ); SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ['||V_DTM||'] GDR_SP_SAMPLE_DELTA - (OKT-01) !!');

	--COMMIT;
V_STM := GDR_SF_CHECKTIME( V_STM, V_DTM ); SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ['||V_DTM||'] GDR_SP_SAMPLE_DELTA - END !!');

EXCEPTION
    WHEN OTHERS THEN
		V_SQLCODE := SQLCODE ;
		V_SQLERRM := SQLERRM ;
		SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] [ERROR] A_SAMPLE_ID = '||A_SAMPLE_ID );
		SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ERR-'||SQLCODE||' '||SQLERRM );
		SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ERR-'||V_SQLCODE||' '||V_SQLERRM );

		--ROLLBACK;
		RAISE_APPLICATION_ERROR( 990000 + MOD(V_SQLCODE,1000) , V_SQLERRM );	-- ALTIBASE ( 990000 ~ 991000 )
END;
/
