CREATE OR REPLACE FUNCTION GDR_SF_CHECKTIME
(
  A_STM			 IN DATE
, A_DTM			OUT NUMBER(15,6)
--, A_POS			OUT NUMBER
)
RETURN DATE
AS
    V_ETM		DATE;
BEGIN
	V_ETM := SYSDATE;
	A_DTM := DATEDIFF( A_STM, V_ETM, 'MICROSECOND') / 1000000.0;
--SYSTEM_.PRINTLN('OKT_01] - '|| DATEDIFF( A_STM, V_ETM, 'MICROSECOND') );
--SYSTEM_.PRINTLN('OKT_03] - '|| A_DTM );

	--IF A_POS IS NOT NULL THEN
		--A_POS := A_POS + 1;
	--END IF;

    RETURN V_ETM;
EXCEPTION
    WHEN OTHERS THEN
		SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ERR-'||SQLCODE||' '||SQLERRM );
	RETURN NULL;
END;
/
