CREATE OR REPLACE FUNCTION GDR_SF_SQLTEXT
(
  A_SID         IN INTEGER
, A_STMT_ID     IN INTEGER
, A_QUERY       IN VARCHAR(32000)       DEFAULT NULL
)
RETURN VARCHAR(32000)
AS
    V_OUTSTR    VARCHAR(32000);
    V_PIECE     VARCHAR(64);
    V_LEN       INTEGER;

    CURSOR C1 IS SELECT TEXT FROM V$SQLTEXT WHERE SID = A_SID AND STMT_ID = A_STMT_ID ORDER BY PIECE LIMIT V_LEN;
BEGIN
    IF LENGTHB( A_QUERY ) <= 16380 THEN -- 16384 (X)
        RETURN A_QUERY ;
    END IF;

    V_LEN := ( 32000 / 64 );
    OPEN C1;
    LOOP
        FETCH C1 INTO V_PIECE;
        EXIT WHEN C1%NOTFOUND;

        V_OUTSTR := V_OUTSTR || V_PIECE ;
    END LOOP;
    CLOSE C1;

    IF V_OUTSTR IS NULL THEN
        RETURN A_QUERY;
    ELSE
        RETURN V_OUTSTR;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ERR-'||SQLCODE||' '||SQLERRM );
        --RAISE;
    RETURN NULL ;
END;
/
