--CREATE TABLE MON_IMSI.GDR_ACTIVE_SESSION_HISTORY
CREATE TABLE GDR_ACTIVE_SESSION_HISTORY
(
    SAMPLE_ID                   NUMBER,
    SAMPLE_TIME                 DATE,
    SESSION_ID                  NUMBER,
    --SESSION_SERIAL#             NUMBER,
    USER_ID                     NUMBER,
    SQL_ID                      VARCHAR2(13),
    SQL_CHILD_NUMBER            NUMBER,
    SQL_PLAN_HASH_VALUE         NUMBER,
    --FORCE_MATCHING_SIGNATURE    NUMBER,
    --SQL_OPCODE                  NUMBER,
    --PLSQL_ENTRY_OBJECT_ID       NUMBER,
    --PLSQL_ENTRY_SUBPROGRAM_ID   NUMBER,
    --PLSQL_OBJECT_ID             NUMBER,
    --PLSQL_SUBPROGRAM_ID         NUMBER,
    --SERVICE_HASH                NUMBER,
    --SESSION_TYPE                VARCHAR2(10),
    SESSION_STATE               VARCHAR2(7),        -- "ON CPU", 
    --QC_SESSION_ID               NUMBER,
    --QC_INSTANCE_ID              NUMBER,
    BLOCKING_SESSION            NUMBER,
    --BLOCKING_SESSION_STATUS     VARCHAR2(11),     -- "NOT IN WAIT", "VALID"
    --BLOCKING_SESSION_SERIAL#    NUMBER,
    EVENT                       VARCHAR2(64),
    EVENT_ID                    NUMBER,
    --EVENT#                      NUMBER,
    --SEQ#                        NUMBER,
    P1TEXT                      VARCHAR2(64),
    P1                          NUMBER,
    --P2TEXT                      VARCHAR2(64),
    --P2                          NUMBER,
    --P3TEXT                      VARCHAR2(64),
    --P3                          NUMBER,
    WAIT_CLASS                  VARCHAR2(64),
    WAIT_CLASS_ID               NUMBER,
    WAIT_TIME                   NUMBER,
    TIME_WAITED                 NUMBER,
    --XID                         RAW(8),
    --CURRENT_OBJ#                NUMBER,
    --CURRENT_FILE#               NUMBER,
    --CURRENT_BLOCK#              NUMBER,
    --CAPTURE_OVERHEAD            VARCHAR2(1),
    --IS_CAPTURED                 VARCHAR2(1),
    --PROGRAM                     VARCHAR2(48),
    MODULE                      VARCHAR2(48),
    --ACTION                      VARCHAR2(32),
    --CLIENT_ID                   VARCHAR2(64),
    MACHINE                     VARCHAR2(64),
    PORT                        NUMBER,
    --ECID                        VARCHAR2(64),
    FLAGS                       NUMBER
)
;

