SELECT * FROM (
SELECT 
       --SID, "SERIAL#" 
       '-- (TODO) [' || SYSDATE || '] ALTer SYSTEM KILL SESSION '''|| SID ||',' || "SERIAL#" ||''' /* '|| S.AUDSID || ', ' || S.IPADDR ||' */ ;' SQL
  FROM V$SESSION S
 WHERE 1=1
   --AND S.SID IN ( SELECT SID FROM V$MYSTAT WHERE ROWNUM = 1 )
   AND S.AUDSID = SYS_CONTEXT('USERENV','SESSIONID')
   AND S.USERNAME IN ( 'US_GDMON' )
   AND S.PROG_NAME LIKE 'tbsql%'
 ORDER BY S.LOGON_TIME DESC
) WHERE ROWNUM <= 2
;

