CREATE OR REPLACE FUNCTION MY_ENCRYPT( INPUT_STRING IN VARCHAR(32000), KEY_STRING IN VARCHAR(40) )
RETURN VARCHAR(100)
AS
    ENCRYPTED_STRING VARCHAR(100);
    PIECES_OF_EIGHT INTEGER;
BEGIN
    PIECES_OF_EIGHT := ((FLOOR(LENGTH(INPUT_STRING)/8 + .9)) * 8);
    ENCRYPTED_STRING := DESENCRYPT( RPAD( INPUT_STRING, PIECES_OF_EIGHT), RPAD( KEY_STRING, 8, '#' ) );
     RETURN ENCRYPTED_STRING;
END;
/
