set linesize 1000;
set pagesize 1000;

SELECT DECODE( ST.EXECUTIONS, 0 , NULL, ROUND( ST.TOTAL_EXEC_TIME/ST.EXECUTIONS , 3 ) ) COST
     , ST.EXECUTIONS, ST.TOTAL_EXEC_TIME, ST.LAST_EXEC_TIME, ST.START_TIME
     , LENGTHB( ST.SQL_TEXT ) LEN
     , SUBSTRB( ST.SQL_TEXT, 1, 80 ) SQLN
     --, ST.SQL_TEXT
     , SS.PROGRAM_NAME
     --, SS.*
     --, ST.*
  FROM V$STATEMENT ST
     , V$SESSION SS
 WHERE SS.SESSION_ID = ST.SESSION_ID
 ORDER BY ST.START_TIME, 1 DESC, 2 DESC
 LIMIT 10
;

