CREATE TABLE ALL_OBJECT_USAGE
(
  OWNER VARCHAR(30) Not Null
, TABLE_NAME VARCHAR(30) Not Null
, INDEX_NAME VARCHAR(30) Not Null
, MONITORING VARCHAR(3) DEFAULT 'YES'
, USED VARCHAR(3) DEFAULT 'NO'
, START_MONITORING DATE DEFAULT SYSDATE
, END_MONITORING DATE
, LAST_MODIFIED DATE DEFAULT SYSDATE
, DESCRIPTION VARCHAR(100)
)
;

ALTER TABLE ALL_OBJECT_USAGE ADD CONSTRAINT IX_ALL_OBJECT_USAGE_PK PRIMARY KEY ( TABLE_NAME, INDEX_NAME, OWNER );
CREATE INDEX IX_ALL_OBJECT_USAGE_X01 ON ALL_OBJECT_USAGE ( INDEX_NAME );


INSERT INTO ALL_OBJECT_USAGE (
OWNER                  
TABLE_NAME             
INDEX_NAME             
MONITORING             
USED                   
START_MONITORING       
END_MONITORING         
LAST_MODIFIED          
DESCRIPTION            
)
SELECT 
INDEX_OWNER          
INDEX_NAME           
TABLE_OWNER          
TABLE_NAME           
COLUMN_NAME          
COLUMN_POSITION      
FROM ALL_IND_COLUMNS
WHERE 1=1
AND OWNER LIKE '%OWN'
AND OBJECT_TYPE = 'INDEX'
