set linesize 200;
set colsize 200;

SELECT 
       'CREATE PUBLIC SYNONYM '||B.PROC_NAME||' FOR '||A.USER_NAME||'.'||B.PROC_NAME||' ;' SQL
  FROM SYSTEM_.SYS_USERS_ A
     , SYSTEM_.SYS_PROCEDURES_ B
 WHERE 1=1
   AND A.USER_ID = B.USER_ID
   --AND B.TABLE_TYPE IN ( 'T', 'S' )
   AND A.USER_NAME IN ('US_xx')
   AND B.PROC_NAME NOT IN ( SELECT C.OBJECT_NAME FROM SYSTEM_.SYS_SYNONYMS_ C WHERE C.SYNONYM_OWNER_ID IS NULL )
   AND 
   NOT
   (
       B.PROC_NAME LIKE '%BCK%'
       OR B.PROC_NAME LIKE '%\_20%' ESCAPE '\'
   )
 ORDER BY 1
;

SELECT 
       'CREATE PUBLIC SYNONYM '||B.TABLE_NAME||' FOR '||A.USER_NAME||'.'||B.TABLE_NAME||' ;' SQL
  FROM SYSTEM_.SYS_USERS_ A
     , SYSTEM_.SYS_TABLES_ B
 WHERE 1=1
   AND A.USER_ID = B.USER_ID
   AND B.TABLE_TYPE IN ( 'T', 'S' )
   AND A.USER_NAME IN ('US_xx')
   AND B.TABLE_NAME NOT IN ( SELECT C.OBJECT_NAME FROM SYSTEM_.SYS_SYNONYMS_ C WHERE C.SYNONYM_OWNER_ID IS NULL )
   AND 
   NOT
   (
       B.TABLE_NAME LIKE '%BCK%'
       OR B.TABLE_NAME LIKE '%\_20%' ESCAPE '\'
   )
 ORDER BY 1
;
