CREATE TABLE US_GDMON.DBA_HIST_SEGMENTS
(
    SNAP_TIME       DATE DEFAULT TRUNC(SYSDATE,'SECOND'),
    OWNER           VARCHAR(40),
    TABLE_NAME      VARCHAR(40),
    SEGMENT_NAME    VARCHAR(40),
    SEGMENT_TYPE    VARCHAR(7),
    TABLESPACE_NAME VARCHAR(40),
    BYTES           BIGINT,
    MBYTES          BIGINT,
    BLOCKS          BIGINT,
    EXTENTS         BIGINT,
    NUM_ROWS        BIGINT,
    CREATED         DATE,
    LAST_DDL_TIME   DATE
)
;

CREATE INDEX US_GDMON.IX_DBA_HIST_SEGMENTS_NI01 ON US_GDMON.DBA_HIST_SEGMENTS (TABLE_NAME,SNAP_TIME DESC) ;
CREATE INDEX US_GDMON.IX_DBA_HIST_SEGMENTS_NI02 ON US_GDMON.DBA_HIST_SEGMENTS (SEGMENT_NAME,SNAP_TIME DESC) ;
CREATE INDEX US_GDMON.IX_DBA_HIST_SEGMENTS_NI03 ON US_GDMON.DBA_HIST_SEGMENTS (TABLESPACE_NAME,SNAP_TIME DESC) ;
ALTER TABLE US_GDMON.DBA_HIST_SEGMENTS ADD CONSTRAINT IX_DBA_HIST_SEGMENTS_PK PRIMARY KEY (OWNER,TABLE_NAME,SEGMENT_NAME,SEGMENT_TYPE,SNAP_TIME) ;

GRANT SELECT ON US_GDMON.DBA_HIST_SEGMENTS TO PUBLIC;
--GRANT UPDATE ON US_GDMON.DBA_HIST_SEGMENTS TO US_GDMON;
--GRANT INSERT ON US_GDMON.DBA_HIST_SEGMENTS TO US_GDMON;
--GRANT DELETE ON US_GDMON.DBA_HIST_SEGMENTS TO US_GDMON;

CREATE PUBLIC SYNONYM DBA_HIST_SEGMENTS FOR US_GDMON.DBA_HIST_SEGMENTS;

