WITH WX AS
(
SELECT TABLE_OWNER
     , TABLE_NAME
     , INDEX_NAME
     , MAX(C1) C1
     , MAX(C2) C2
     , MAX(C3) C3
     , MAX(C4) C4
     , MAX(C5) C5
     , MAX(C6) C6
     , MAX(C7) C7
     , MAX(C8) C8
     , MAX(C9) C9
  FROM
(
SELECT TABLE_OWNER
     , TABLE_NAME
     , INDEX_NAME
     , DECODE(COLUMN_POSITION,1,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C1
     , DECODE(COLUMN_POSITION,2,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C2
     , DECODE(COLUMN_POSITION,3,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C3
     , DECODE(COLUMN_POSITION,4,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C4
     , DECODE(COLUMN_POSITION,5,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C5
     , DECODE(COLUMN_POSITION,6,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C6
     , DECODE(COLUMN_POSITION,7,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C7
     , DECODE(COLUMN_POSITION,8,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C8
     , DECODE(COLUMN_POSITION,9,COLUMN_NAME || DECODE(DESCEND,'DESC',' DESC',NULL) , NULL) C9
  FROM ALL_IND_COLUMNS A
 WHERE 1=1
   --AND INDEX_OWNER != TABLE_OWNER
   AND TABLE_OWNER LIKE '%OWN'
   --AND TABLE_NAME LIKE '%\_IF%' ESCAPE '\'
   --AND DESCEND != 'ASC'
 ORDER BY TABLE_OWNER, TABLE_NAME, INDEX_NAME, COLUMN_POSITION
 --LIMIT 1
)
 GROUP BY TABLE_OWNER, TABLE_NAME, INDEX_NAME
 ORDER BY TABLE_OWNER, TABLE_NAME, INDEX_NAME
)
SELECT TABLE_OWNER
     , TABLE_NAME
     , INDEX_NAME
     , C1 ||NVL2(C1,', ',NULL) ||C2 ||NVL2(C2,', ',NULL) ||C3 ||NVL2(C3,', ',NULL) ||C4 ||NVL2(C4,', ',NULL) ||C5 ||NVL2(C5,', ',NULL) ||C6 ||NVL2(C6,', ',NULL) ||C7 ||NVL2(C7,', ',NULL) ||C8 ||NVL2(C8,', ',NULL) ||C9 COLS
     , C1
     , C2
     , C3
     , C4
     , C5
     , C6
     , C7
     , C8
     , C9
  FROM WX
;

