CREATE TABLE SYS.SUM_TABLE_ALL_SEGMENTS
(
    SNAP_TIME       DATE DEFAULT TRUNC(SYSDATE,'SECOND'),
    OWNER           VARCHAR(40),
    TABLE_NAME      VARCHAR(40),
    SEGMENT_NAME    VARCHAR(40),
    SEGMENT_TYPE    VARCHAR(7),
    TABLESPACE_NAME VARCHAR(40),
    BYTES           BIGINT,
    MBYTES          BIGINT,
    BLOCKS          BIGINT,
    EXTENTS         BIGINT,
    NUM_ROWS        BIGINT,
    CREATED         DATE,
    LAST_DDL_TIME   DATE
)
PCTFREE 5;

CREATE INDEX SYS.IX_SUM_TABLE_ALL_SEGMENTS_NI01
ON SYS.SUM_TABLE_ALL_SEGMENTS
(TABLE_NAME,SNAP_TIME DESC)
;

CREATE INDEX SYS.IX_SUM_TABLE_ALL_SEGMENTS_NI02
ON SYS.SUM_TABLE_ALL_SEGMENTS
(SEGMENT_NAME,SNAP_TIME DESC)
;

CREATE INDEX SYS.IX_SUM_TABLE_ALL_SEGMENTS_NI03
ON SYS.SUM_TABLE_ALL_SEGMENTS
(TABLESPACE_NAME,SNAP_TIME DESC)
;

ALTER TABLE SYS.SUM_TABLE_ALL_SEGMENTS
ADD CONSTRAINT IX_SUM_TABLE_ALL_SEGMENTS_PK PRIMARY KEY (OWNER,TABLE_NAME,SEGMENT_NAME,SEGMENT_TYPE,SNAP_TIME);
