@off

DROP TABLE OKT ;
CREATE TABLE OKT ( ID VARCHAR(10), PARENT VARCHAR(10) );
CREATE INDEX IX_OKT_ID ON OKT (ID);
CREATE INDEX IX_OKT_PARENT ON OKT (PARENT);

INSERT INTO OKT VALUES ( 10, 0 );
INSERT INTO OKT VALUES ( 11, 10 );
INSERT INTO OKT VALUES ( 12, 10 );
INSERT INTO OKT VALUES ( 20, 10 );
INSERT INTO OKT VALUES ( 21, 20 );
INSERT INTO OKT VALUES ( 30, 10 );
INSERT INTO OKT VALUES ( 90, 0 );

COMMIT;

@on

SELECT 
       /*+ RULE */
       ID
     , CAST(SYS_CONNECT_BY_PATH(ID, '/') AS VARCHAR(20)) "PATH"
  FROM OKT
 --START WITH ID = 0
 START WITH ID = 10
 CONNECT BY PRIOR ID = PARENT
;
