CREATE OR REPLACE PROCEDURE SYS.SP_TABLE_INFO
(
  A_TABLE_NAME in VARCHAR(40)
, A_USER_NANE  in VARCHAR(40) DEFAULT NULL
) AS
    V_USER_NAME VARCHAR(40);
    V_TABLE_NAME VARCHAR(40);
    V_TABLE_TYPE VARCHAR(40);
    V_TABLE_ID VARCHAR(40);
    V_TABLE_OID VARCHAR(40);
    V_SQL VARCHAR(1024);
    V_CNT_TB NUMBER(19);
    V_CNT_IX NUMBER(19);
    V_CNT_COL NUMBER(19);
    V_CNT_FK1 NUMBER(19);
    V_CNT_FK2 NUMBER(19);
    V_CNT NUMBER(19);
    V_SZ_TB NUMERIC(10,3);
    V_SZ_IX NUMERIC(10,3);
    V_LEN20 NUMBER(19);
    V_LEN05 NUMBER(19);
    V_LEN12 NUMBER(19);

    CURSOR C1
    IS
    SELECT U.USER_NAME
         , T.TABLE_NAME
         --, DECODE(T.TABLE_TYPE,'T','TABLE','V','VIEW','S','SEQ') TABLE_TYPE
         , CASE WHEN TBS.TYPE IN (0,1,2) THEN 'M'
                WHEN TBS.TYPE IN (3,4) THEN 'D'
                WHEN TBS.TYPE IN (8) THEN 'V'
                ELSE T.TABLE_TYPE
            END AS TABLE_TYPE
         , T.TABLE_ID
         , T.TABLE_OID
      FROM SYSTEM_.SYS_USERS_ U
         , SYSTEM_.SYS_TABLES_ T
         , V$TABLESPACES TBS
     WHERE U.USER_ID = T.USER_ID
       --AND U.USER_NAME LIKE 'US_%OWN'
       AND U.USER_NAME LIKE NVL(A_USER_NANE, 'US_%OWN')
       AND T.TABLE_NAME LIKE UPPER(A_TABLE_NAME)
       AND T.TABLE_TYPE = 'T'
       AND TBS.ID = T.TBS_ID
     ORDER BY U.USER_NAME, T.TABLE_NAME
    ;

BEGIN

    SELECT
        MAX( LENGTH(T.TABLE_NAME) )
        INTO V_LEN20
    FROM
        SYSTEM_.SYS_USERS_ U,
        SYSTEM_.SYS_TABLES_ T
    WHERE
        U.USER_ID = T.USER_ID
        AND T.TABLE_NAME LIKE UPPER(A_TABLE_NAME)
        AND T.TABLE_TYPE = 'T'
    ;

    V_LEN20 := CASE2( V_LEN20>20, V_LEN20, 20 );
    V_LEN05 := 5;
    V_LEN12 := 14;

    OPEN C1;

    SYSTEM_.PRINTLN( RPAD('OWNER',V_LEN12)||' |'||RPAD('TNAME',V_LEN20)||' |'||RPAD('TABTYPE',V_LEN05)||' |'||
LPAD('COL#',V_LEN05)||' |'||LPAD('NUM_ROWS',V_LEN12)||' |'||LPAD('TB (MB)',V_LEN12)||' |'||LPAD('IXs (MB)',V_LEN12)||' |'||
LPAD('IX#',V_LEN05)||' |'||LPAD('F_FK#',V_LEN05)||' |'||LPAD('T_FK#',V_LEN05) );
    SYSTEM_.PRINTLN( RPAD('-',120,'-') );

    V_CNT := 0;
    LOOP
        V_CNT_IX := NULL;
        V_CNT_FK1 := NULL;
        V_CNT_FK2 := NULL;

        FETCH C1 INTO V_USER_NAME, V_TABLE_NAME, V_TABLE_TYPE, V_TABLE_ID, V_TABLE_OID;
        EXIT WHEN C1%NOTFOUND;

        --IF V_TABLE_TYPE = 'TABLE' THEN
        IF V_TABLE_TYPE IN ('D', 'M', 'V') THEN

            -- UNIQUE CONSTRAINT (BUG)
            select COUNT(*) into V_CNT_IX from SYSTEM_.SYS_INDICES_ where TABLE_ID = V_TABLE_ID ;

            -- COL#
            select COUNT(*) into V_CNT_COL from SYSTEM_.SYS_COLUMNS_ where TABLE_ID = V_TABLE_ID ;


            /* CONSTRAINT_TYPE : 1 - NOT NULL, 2 - UNIQUE, 3 - PK, 0 - FK */
            SELECT COUNT(*) INTO V_CNT_FK1
              FROM SYSTEM_.SYS_CONSTRAINTS_
             WHERE TABLE_ID = V_TABLE_ID AND CONSTRAINT_TYPE = 0 ;

            SELECT COUNT(*) INTO V_CNT_FK2
              FROM SYSTEM_.SYS_CONSTRAINTS_
             WHERE REFERENCED_TABLE_ID = V_TABLE_ID AND CONSTRAINT_TYPE = 0;

            -- # COUNT
            V_SQL := 'SELECT COUNT(*) FROM '||V_USER_NAME||'.'||V_TABLE_NAME;
            EXECUTE IMMEDIATE V_SQL INTO V_CNT_TB;

            -- # TB SZ (MB)
            V_SQL := '
SELECT ROUND(C.EXTENT_PAGE_COUNT * C.PAGE_SIZE * D.EXTENT_TOTAL_COUNT/1024/1024, 3) ALLOC
  FROM V$TABLESPACES C, V$SEGMENT D
 WHERE 1 = 1
   AND C.ID = D.SPACE_ID
   AND D.TABLE_OID = ?
   AND D.SEGMENT_TYPE=''TABLE''
 UNION ALL
SELECT ROUND((C.FIXED_ALLOC_MEM+C.VAR_ALLOC_MEM)/1024/1024,3) ALLOC
  FROM V$MEMTBL_INFO C
 WHERE 1=1
   AND C.TABLE_OID = ?
';
            BEGIN
                EXECUTE IMMEDIATE V_SQL into V_SZ_TB using V_TABLE_OID, V_TABLE_OID;
            EXCEPTION
                WHEN OTHERS THEN
                    -- IF NOT FOUND, THEN MEMTBL
                    SYSTEM_.PRINTLN( 'V_TABLE_OID='||V_TABLE_OID );
                    RAISE;
            END;


            -- # IX SZ SUM (MB)
            IF V_TABLE_TYPE IN ('M', 'V') THEN
                V_SZ_IX := ROUND( V_CNT_IX*V_CNT_TB*16/1024/1024, 3 );
            ELSE -- 'D'
                V_SQL := '
SELECT SUM(ROUND(C.EXTENT_PAGE_COUNT * C.PAGE_SIZE * D.EXTENT_TOTAL_COUNT/1024/1024, 3)) ALLOC
  FROM V$TABLESPACES C, V$SEGMENT D, V$INDEX E
 WHERE 1 = 1
   AND C.ID = D.SPACE_ID
   AND D.TABLE_OID = ?
   AND D.SEGMENT_TYPE = ''INDEX''
   AND D.SEGMENT_PID = E.INDEX_SEG_PID
   --AND D.TABLE_OID = E.TABLE_OID
';
                EXECUTE IMMEDIATE V_SQL INTO V_SZ_IX USING V_TABLE_OID;
            END IF;

        END IF;

        SYSTEM_.PRINTLN( RPAD(V_USER_NAME,V_LEN12)||' |'||RPAD(V_TABLE_NAME,V_LEN20)||' |'||RPAD(V_TABLE_TYPE,V_LEN05)||' |'||
LPAD(V_CNT_COL,V_LEN05)||' |'||LPAD(TRIM(TO_CHAR(V_CNT_TB,'9,999,999,999')),V_LEN12)||' |'||LPAD(TRIM(TO_CHAR(V_SZ_TB,'9,999,999.9')),V_LEN12)||' |'||LPAD(TRIM(TO_CHAR(NVL(V_SZ_IX,0),'9,999,999.9')),V_LEN12)||' |'||
LPAD(NVL(V_CNT_IX,0),V_LEN05)||' |'||LPAD(NVL(V_CNT_FK1,0),V_LEN05)||' |'||LPAD(NVL(V_CNT_FK2,0),V_LEN05) );

        V_CNT := V_CNT + 1;
    END LOOP;

    CLOSE C1;

    SYSTEM_.PRINTLN( RPAD('-',120,'-') );
    SYSTEM_.PRINTLN( V_CNT||' rows selected.' );
END;
/
