SELECT 
       LAST_DDL_TIME
     , A.* 
  FROM DBA_OBJECTS A
 WHERE 1=1
   --AND LAST_DDL_TIME > SYSDATE - 4/24
   AND OWNER NOT IN ( 'SYS', 'SYSTEM' , 'CTXSYS' )
   AND OBJECT_TYPE NOT IN ( 'PACKAGE BODY', 'PROCEDURE', 'TRIGGER', 'PACKAGE' )
   AND OBJECT_NAME LIKE '%xx%'
 ORDER BY A.LAST_DDL_TIME DESC
;
