-- 10g Only

set linesize 220;
set pagesize 1000;

col JOB_NAME format a40;
col SCHEDULE_NAME format a40;
col PROGRAM_OWNER format a40;
col PROGRAM_NAME format a40;
col PROGRAM_ACTION format a40;


SELECT * FROM TABLE(
SELECT 1
     , JOB_NAME
     , SCHEDULE_NAME, J.PROGRAM_OWNER, J.PROGRAM_NAME
     , P.PROGRAM_ACTION, P.NUMBER_OF_ARGUMENTS
     , CAST( J.LAST_START_DATE AS TIMESTAMP WITH LOCAL TIME ZONE ) LAST_START_DATE
     , LAST_RUN_DURATION, STOP_ON_WINDOW_CLOSE
  FROM DBA_SCHEDULER_JOBS J, DBA_SCHEDULER_PROGRAMS P
 WHERE 1=1
   --AND J.JOB_NAME = 'GATHER_STATS_JOBS'
   AND P.PROGRAM_NAME = J.PROGRAM_NAME
)
;

