-- 인덱스 생성소요시간을 DB Meta에서 조회하는 쿼리
-- alert 로그를 통해 조회하는 방식으로 최대 10초 과소 측정될 수 있음
-- X$DBGALERTEXT 를 조회하므로 SYS 계정으로 수행필요

WITH 
W1 AS
(
SELECT IX.OWNER
     , TABLE_NAME
     , INDEX_NAME
     , UNIQUENESS
     , LEAF_BLOCKS
     , NUM_ROWS
     , DISTINCT_KEYS
     , DECODE(LEAF_BLOCKS,0,0,TRUNC(NUM_ROWS/LEAF_BLOCKS)) "Rows/BLK"
     , PARTITIONED
     , LOGGING
     , DEGREE
     , BLEVEL
     , PCT_FREE
     --, IX.TEMPORARY, VISIBILITY, BUFFER_POOL, FLASH_CACHE, CELL_FLASH_CACHE
     , LAST_ANALYZED
     , OB.CREATED
  FROM DBA_INDEXES IX
       INNER JOIN DBA_OBJECTS OB 
               ON OB.OWNER = IX.OWNER
              AND OB.OBJECT_NAME = IX.INDEX_NAME
              AND OB.OBJECT_TYPE LIKE 'INDEX'
              AND OB.STATUS = 'VALID'
              AND NOT REGEXP_LIKE(OBJECT_NAME, '_BAK|_OKT|_SJR')
 WHERE 1=1
   AND IX.OWNER IN ('CODADM', 'ISDADM')   
   --AND INDEX_NAME = 'PK_ISD_0050NT'
) , 
W2 AS
(
SELECT ORIGINATING_TIMESTAMP, UPPER(MESSAGE_TEXT) MESSAGE_TEXT
  FROM SYS.X$DBGALERTEXT a
 WHERE ORIGINATING_TIMESTAMP > SYSDATE - 30
   AND UPPER(MESSAGE_TEXT) LIKE '%CREATE%INDEX% ON %'
)
SELECT X.*, TRUNC((LOG_DATE - CREATED) * 24 * 60 * 60) "Elapsed,s"
  FROM (
       SELECT W1.*
            , (SELECT TO_DATE(TO_CHAR(MAX(ORIGINATING_TIMESTAMP),'YYYY/MM/DD HH24:MI:SS'),'YYYY/MM/DD HH24:MI:SS')
                 FROM W2
                WHERE REGEXP_LIKE(MESSAGE_TEXT, 'CREATE.*INDEX.*("|\.| )'||W1.INDEX_NAME||'("| )[ ]*ON[ ]*')
              ) LOG_DATE
         from W1
        WHERE 1=1
       ) X
 --WHERE LOG_DATE IS NOT NULL
 ORDER BY CREATED DESC
;


