-- DATA DICTIONARY CACHE HIT RATIO
SELECT SYSDATE, (1-(SUM(getmisses)/SUM(gets))) * 100 "Hit Ratio" FROM V$ROWCACHE;

-- LIBRARY CACHE HIT RATIO
SELECT SYSDATE
     , 'SHAREDPOOL_HIT_RATIO' AS SHAREDPOOL_HIT_RATIO
     , ROUND(100.0 * sum(PINHITS) / sum(pins),2) as VALUE
FROM V$LIBRARYCACHE;
