SELECT IS_BIND_SENSITIVE
     , IS_BIND_AWARE
     , IS_SHAREABLE
     , COUNT(*)
  FROM V$SQL A
 WHERE 1=1
   AND IS_SHAREABLE <> 'N'
 GROUP BY IS_BIND_SENSITIVE, IS_BIND_AWARE, IS_SHAREABLE
 ORDER BY IS_BIND_SENSITIVE, IS_BIND_AWARE, IS_SHAREABLE
;
