SELECT I.OWNER
     , I.TABLE_NAME
     , I.INDEX_NAME
     , I.LEAF_BLOCKS*8192/1024/1024 as MB
     , I.TABLESPACE_NAME
     , I.*
  FROM DBA_INDEXES I
 WHERE 1=1
   AND I.OWNER IN ('MON_IMSI')
 ORDER BY I.OWNER, I.TABLE_NAME, I.INDEX_NAME
;
