CREATE OR REPLACE FUNCTION TO_DATE_OKT
(
  P_TEXT		IN VARCHAR2
, P_FMT			IN VARCHAR2
, P_OPT			IN VARCHAR2 DEFAULT NULL
)
RETURN DATE
AS
    V_DATE		DATE;
BEGIN
 
	IF P_OPT IS NULL THEN
		V_DATE := TO_DATE(P_TEXT, P_FMT);
	ELSE
		V_DATE := TO_DATE(P_TEXT, P_FMT, P_OPT);
	END IF;

	RETURN V_DATE;

EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
/
