SELECT SNAPTIME
     , OWNER
     , TABLE_NAME
     , SUM(U1_INSERT)
     , SUM(U1_DELETE)
     , SUM(U1_UPDATE)
     , SUM(U2_INSERT)
     , SUM(U2_DELETE)
     , SUM(U2_UPDATE)
     , SUM(U3_INSERT)
     , SUM(U3_DELETE)
     , SUM(U3_UPDATE)
     , SUM(OTH_INSERT)
     , SUM(OTH_DELETE)
     , SUM(OTH_UPDATE)
  FROM (SELECT /*+ ALL_ROWS */
               TO_CHAR(B.TIMESTAMP,'YYYY/MM/DD HH24') AS SNAPTIME
             , A.OWNER AS OWNER
             , A.TABLE_NAME AS TABLE_NAME
             , DECODE(A.OWNER, 'U1', B.INSERTS,0) AS U1_INSERT
             , DECODE(A.OWNER, 'U1', B.DELETES,0) AS U1_DELETE
             , DECODE(A.OWNER, 'U1', B.UPDATES,0) AS U1_UPDATE
             , DECODE(A.OWNER, 'U2', B.INSERTS,0) AS U2_INSERT
             , DECODE(A.OWNER, 'U2', B.DELETES,0) AS U2_DELETE
             , DECODE(A.OWNER, 'U2', B.UPDATES,0) AS U2_UPDATE
             , DECODE(A.OWNER, 'U3', B.INSERTS,0) AS U3_INSERT
             , DECODE(A.OWNER, 'U3', B.DELETES,0) AS U3_DELETE
             , DECODE(A.OWNER, 'U3', B.UPDATES,0) AS U3_UPDATE
             , CASE WHEN A.OWNER NOT IN ('U1','U2','U3') THEN B.INSERTS END AS OTH_INSERT
             , CASE WHEN A.OWNER NOT IN ('U1','U2','U3') THEN B.DELETES END AS OTH_DELETE
             , CASE WHEN A.OWNER NOT IN ('U1','U2','U3') THEN B.UPDATES END AS OTH_UPDATE
          FROM SYS.DBA_TABLES A
          JOIN SYS.DBA_TAB_MODIFICATIONS B
            ON 1=1
           AND B.TABLE_OWNER = A.OWNER
           AND B.TABLE_NAME = A.TABLE_NAME
           AND ( B.INSERTS + B.DELETES + B.UPDATES ) > 0
           AND B.TIMESTAMP >= TRUNC(SYSDATE-4) )
         WHERE 1=1
           AND A.OWNER NOT IN ('SYS' ,'SYSTEM','CTXSYS')
           AND A.MONITORING = 'YES'
 GROUP BY SNAPTIME, A.OWNER, A.TABLE_NAME
 ORDER BY 1,2,3 ;
 
