
CREATE DATABASE LINK LK_ORCL
CONNECT TO US_GDMON IDENTIFIED BY US_GDMON
USING 
'(DESCRIPTION = 
    (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))
    (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCL))
 )'
;
