-- 추출SQL

SELECT
       A.OWNER
     , A.TABLE_NAME
     , ROUND(SUM(TABLE_SIZE)/1024/1024,3) "TABLE_SIZE,M"
     , ROUND(SUM(LOB_SIZE)/1024/1024,3) "LOB_SIZE,M"
     , SUM(LOB_CNT) "LOB_CNT"
     , ROUND(SUM(INDEX_SIZE)/1024/1024,3) "INDEX_SIZE,M"
     , SUM(INDEX_CNT) "INDEX_CNT"
     , ROUND(SUM(TABLE_SIZE)/1024/1024 + SUM(LOB_SIZE)/1024/1024 + SUM(INDEX_SIZE)/1024/1024,3) "ALL_SIZE,M"
  FROM 
(
-- (1) TABLE_SIZE
SELECT A.OWNER
     , B.TABLE_NAME
     , SUM(SEG_SIZE) TABLE_SIZE
     , 0 LOB_SIZE
     , 0 LOB_CNT
     , 0 INDEX_SIZE
     , 0 INDEX_CNT
  FROM (SELECT A.OWNER
             , SEGMENT_NAME
             , SUM(BYTES) SEG_SIZE
          FROM DBA_SEGMENTS A
         WHERE A.OWNER IN (SELECT USERNAME FROM DBA_USERS WHERE DEFAULT_TABLESPACE NOT IN ('SYSTEM' ,'SYSAUX' ,'ADAMS'))
           AND A.SEGMENT_TYPE LIKE 'TABLE%'
         GROUP BY A.OWNER,SEGMENT_NAME ) A
     , DBA_TABLES B
 WHERE A.OWNER = B.OWNER(+)
   AND A.SEGMENT_NAME = B.TABLE_NAME
 GROUP BY A.OWNER, B.TABLE_NAME
 UNION ALL
-- (2) INDEX_SIZE
SELECT A.OWNER
     , B.TABLE_NAME
     , 0 TABLE_SIZE
     , 0 LOB_SIZE
     , 0 LOB_CNT
     , SUM(SEG_SIZE) INDEX_SIZE
     , COUNT(*) INDEX_CNT
  FROM (SELECT A.OWNER
             , SEGMENT_NAME
             , SUM(BYTES) SEG_SIZE
          FROM DBA_SEGMENTS A
         WHERE A.OWNER IN (SELECT USERNAME FROM DBA_USERS WHERE DEFAULT_TABLESPACE NOT IN ('SYSTEM' ,'SYSAUX' ,'ADAMS'))
           AND A.SEGMENT_TYPE LIKE 'INDEX%'
         GROUP BY A.OWNER,SEGMENT_NAME ) A
     , DBA_INDEXES B
 WHERE A.OWNER = B.OWNER(+)
   AND A.SEGMENT_NAME = B.INDEX_NAME
 GROUP BY A.OWNER, B.TABLE_NAME 
 UNION ALL
-- (3) LOB_SIZE
SELECT A.OWNER
     , B.TABLE_NAME
     , 0 TABLE_SIZE
     , SUM(SEG_SIZE) LOB_SIZE
     , COUNT(*) LOB_CNT
     , 0 INDEX_SIZE
     , 0 INDEX_CNT
  FROM (SELECT A.OWNER
             , SEGMENT_NAME
             , SEGMENT_TYPE
             ,COUNT(*)
             , SUM(BYTES) SEG_SIZE
          FROM DBA_SEGMENTS A
         WHERE A.OWNER IN (SELECT USERNAME FROM DBA_USERS WHERE DEFAULT_TABLESPACE NOT IN ('SYSTEM' ,'SYSAUX' ,'ADAMS'))
           AND A.SEGMENT_TYPE LIKE 'LOB%'
         GROUP BY A.OWNER,SEGMENT_NAME,SEGMENT_TYPE ) A
     , DBA_LOBS B
 WHERE A.OWNER = B.OWNER(+)
   AND A.SEGMENT_NAME = DECODE(SEGMENT_TYPE,'LOB PARTITION', B.SEGMENT_NAME , 'LOBSEGMENT', B.SEGMENT_NAME,'LOBINDEX', B.INDEX_NAME, B.SEGMENT_NAME)
 GROUP BY A.OWNER, B.TABLE_NAME
) A
 WHERE 1=1
 GROUP BY A.OWNER, A.TABLE_NAME
 ORDER BY 1,2 
;


