
--SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR( SQL_ID => '&SQL_ID' , CURSOR_CHILD_NO => &CURSOR_CHILD_NO ) );
SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR( SQL_ID => '&&SQL_ID' , CURSOR_CHILD_NO => &CURSOR_CHILD_NO ) );

