-- 특정 INDEX를 사용하는 SQL 찾기 
SELECT PARSING_SCHEMA_NAME
     , MODULE
     , FIRST_LOAD_TIME
     , LAST_ACTIVE_TIME
     , EXECUTIONS
     , SQL_ID
     , LENGTH( SQL_FULLTEXT ) LEN
     , SQL_FULLTEXT
     , FETCHES
     , USER_IO_WAIT_TIME
     , ROWS_PROCESSED
     , CPU_TIME
     , ELAPSED_TIME
     , PHYSICAL_READ_BYTES
  FROM V$SQLAREA A
 WHERE 1=1
   AND A.PARSING_SCHEMA_NAME NOT IN ( 'MON_IMSI' )
   AND A.SQL_ID IN 
       (SELECT DISTINCT SQL_ID
          FROM V$SQL_PLAN
         WHERE 1=1
           AND OBJECT_NAME = 'ARTP_BALC_HIST_2018_X03' ) 
;
