set linesize 180;

SELECT SYSDATE
     , ROUND(PGA_TARGET_FOR_ESTIMATE/1024/1024,0) "PGA_TARGET_FOR_ESTIMATE(M)"
     , PGA_TARGET_FACTOR
     , ROUND(ESTD_EXTRA_BYTES_RW/1024/1024,0) "ESTD_EXTRA_BYTES_RW(M)"
     , ESTD_PGA_CACHE_HIT_PERCENTAGE
     , ESTD_OVERALLOC_COUNT
  FROM V$PGA_TARGET_ADVICE
 ORDER BY PGA_TARGET_FACTOR
;
