SET TIMING OFF;
SET HEADING OFF;
SET LINESIZE 120;
SET SERVEROUTPUT ON;
SET AUTOPRINT ON;
SET DEFINE ON;

VAR P_RC_1 REFCURSOR;
VAR P_RC_2 REFCURSOR;

DECLARE
    --V_RC SYS_REFCURSOR;
    V_SQL   VARCHAR2(4000);
    V_STR   VARCHAR2(32);
    V_CHK   NUMBER(2);
BEGIN
    V_STR := '&1';

    -- NEW on ' 12gR2 '
    SELECT COUNT(*) INTO V_CHK FROM V$VERSION WHERE BANNER LIKE '%Oracle Database 12c%12.2%';

--OPEN :P_RC_2 FOR SELECT 1, 2 FROM DUAL UNION ALL SELECT 2, NULL FROM DUAL; RETURN;

    V_SQL := V_SQL|| '
SELECT
       RPAD(PROPERTY_NAME,48)||'' = ''||RPAD(PROPERTY_VALUE||'' '',48)
       AS VALUE
  FROM DATABASE_PROPERTIES A
 WHERE 1=1
   AND ( UPPER(PROPERTY_NAME) LIKE ''%''||UPPER(:V_STR)||''%'' OR PROPERTY_VALUE LIKE ''%''||UPPER(:V_STR)||''%'' )
';
    --OPEN :P_RC_1 FOR V_SQL USING V_STR, V_STR; RETURN;

    V_SQL := V_SQL|| '
 UNION ALL
SELECT
       RPAD(NAME,48)||'' = ''||RPAD(VALUE||'' '',48) ||
       CASE WHEN A.DEFAULT_VALUE IS NOT NULL
                 AND ( ( VALUE IS NULL AND A.DEFAULT_VALUE != ''NULL'' ) OR ( A.DEFAULT_VALUE <> VALUE ) )
            THEN ''(DEF) ''||A.DEFAULT_VALUE 
            ELSE ''(SAME)''
        END AS VALUE
';

    DBMS_OUTPUT.PUT_LINE( '@@ (1) V_CHK='||V_CHK );

    IF V_CHK = 1 THEN

        DBMS_OUTPUT.PUT_LINE( '@@ (2) V_CHK='||V_CHK );
        -- if ' 12gR2 '
        V_SQL := V_SQL||'
  FROM V$PARAMETER A
';

    ELSE

        DBMS_OUTPUT.PUT_LINE( '@@ (3) V_CHK='||V_CHK );
        V_SQL := V_SQL||'
  FROM V$PARAMETER B
       LEFT OUTER JOIN ( SELECT NAME NAME_, DEFAULT_VALUE FROM US_GDMON.OKT_PARAMETER_12GR2 ) A
               ON A.NAME_ = B.NAME
';

    END IF;

    V_SQL := V_SQL|| '
 WHERE 1=1
   AND ( UPPER(NAME) LIKE ''%''||UPPER(:V_STR)||''%'' OR VALUE LIKE ''%''||UPPER(:V_STR)||''%'' OR A.DEFAULT_VALUE LIKE ''%''||UPPER(:V_STR)||''%'' )
';

    IF 1 = 1 THEN

        V_SQL := V_SQL|| '
 UNION ALL
SELECT
       RPAD(X.KSPPINM,48)||'' = ''||RPAD(Y.KSPPSTVL||'' '',48) ||
       CASE WHEN Y.KSPPSTDVL IS NOT NULL
                 AND ( ( Y.KSPPSTVL IS NULL AND Y.KSPPSTDVL != ''NULL'' ) OR ( Y.KSPPSTDVL <> Y.KSPPSTVL ) )
            THEN ''(DEF) ''||Y.KSPPSTDVL
            ELSE ''(SAME)''
        END AS VALUE
     --, X.KSPPDESC
  FROM US_GDMON.OKT_KSPPI X
     , US_GDMON.OKT_KSPPCV Y
 WHERE 1=1
   AND X.INDX = Y.INDX
   AND SUBSTR(X.KSPPINM, 1, 1) = ''_''
   AND ( UPPER( X.KSPPINM ) LIKE ''%''||UPPER(:V_STR)||''%'' OR Y.KSPPSTVL LIKE ''%''||UPPER(:V_STR)||''%'' OR Y.KSPPSTDVL LIKE ''%''||UPPER(:V_STR)||''%'' )
';
    END IF;

    V_SQL := V_SQL|| '
ORDER BY 1
';

    --DBMS_OUTPUT.PUT_LINE( 'V_STR=['||V_STR||']');
    --DBMS_OUTPUT.PUT_LINE( 'V_SQL=['||V_SQL||']');

    --OPEN :P_RC_1 FOR V_SQL USING V_STR, V_STR;
    --OPEN :P_RC_1 FOR V_SQL USING V_STR, V_STR, V_STR, V_STR, V_STR;
    OPEN :P_RC_1 FOR V_SQL USING V_STR, V_STR, V_STR, V_STR, V_STR, V_STR, V_STR, V_STR;

--OPEN :P_RC_2 FOR SELECT 1, 2 FROM DUAL UNION ALL SELECT 2, NULL FROM DUAL; RETURN;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/
