SELECT SYSDATE
     , SGA_SIZE
     , SGA_SIZE_FACTOR
     , ESTD_DB_TIME
     , ROUND(ESTD_PHYSICAL_READS/1024/1024,0) "ESTD_PHYSICAL_READS(M)"
  FROM V$SGA_TARGET_ADVICE
 ORDER BY SGA_SIZE_FACTOR
;
 
