!stty erase "^H"
SET TIME ON;
SET TIMING OFF;
SET FEEDBACK OFF;
SET ECHO ON;

ALTER SESSION SET SKIP_UNUSABLE_INDEXES = TRUE;
ALTER SESSION ENABLE PARALLEL DDL;        
ALTER SESSION ENABLE PARALLEL DML;        

ALTER SESSION SET WORKAREA_SIZE_POLICY = MANUAL;
--ALTER SESSION SET HASH_AREA_SIZE = 2147483647;
--ALTER SESSION SET SORT_AREA_SIZE = 2147483647;
--ALTER SESSION SET SORT_AREA_RETAINED_SIZE = 2147483647;
ALTER SESSION SET HASH_AREA_SIZE = 1073741824;
ALTER SESSION SET SORT_AREA_SIZE = 1073741824;
ALTER SESSION SET SORT_AREA_RETAINED_SIZE = 1073741824;
--ALTER SESSION SET HASH_AREA_SIZE = 536870912;
--ALTER SESSION SET SORT_AREA_SIZE = 536870912;
--ALTER SESSION SET SORT_AREA_RETAINED_SIZE = 536870912;
--ALTER SESSION SET SORT_AREA_SIZE = 10485760;

SET TIMING ON;
SET FEEDBACK ON;

--ALTER SESSION SET WORKAREA_SIZE_POLICY=AUTO;

--ALTER SYSTEM SET SORT_AREA_SIZE = 1048576 DEFERRED SCOPE=BOTH ; 
--(X) ALTER SYSTEM SET HASH_AREA_SIZE = 2097152 DEFERRED SCOPE=BOTH ; 

-- ALTER SYSTEM SET AUDIT_TRAIL=NONE SCOPE=SPFILE;
-- ALTER SYSTEM SET "_DIAG_HM_RC_ENABLED"=FALSE;
-- ALTER SYSTEM SET "_OPTIMIZER_COMPUTE_INDEX_STATS" = FALSE;
-- ALTER SYSTEM SET DB_FILE_MULTIBLOCK_READ_COUNT=256 SCOPE=BOTH;
-- ALTER SYSTEM SET AQ_TM_PROCESSES=1 SCOPE=SPFILE;
-- ALTER SYSTEM SET STREAMS_POOL_SIZE=300M SCOPE=SPFILE;
-- ALTER SYSTEM SET "_DISABLE_STREAMS_POOL_AUTO_TUNING"=TRUE SCOPE=SPFILE;
-- ALTER SYSTEM SET DDL_LOCK_TIMEOUT=3;


