DROP TABLE GDR_HIST_SAMPLESHOT;
CREATE TABLE GDR_HIST_SAMPLESHOT
(
  SAMPLE_ID					NUMBER
, SAMPLE_TIME				DATE
, SAMPLE_INTERVAL			NUMBER(15,3)
--, BEGIN_INTERVAL_TIME		DATE
--, END_INTERVAL_TIME		DATE
--, SAMPLE_LEVEL			NUMBER
, SQLAREA_UPDATE_TIME		DATE
)
--TABLESPACE VOL_TS
;

-- alter table GDR_HIST_SAMPLESHOT add column ( SAMPLE_INTERVAL NUMBER(15,6) );

DROP INDEX IX_GDR_HIST_SAMPLESHOT_NI01;
DROP INDEX IX_GDR_HIST_SAMPLESHOT_NI02;

-- VOL_TS
CREATE UNIQUE INDEX IX_GDR_HIST_SAMPLESHOT_NI01 ON GDR_HIST_SAMPLESHOT ( SAMPLE_ID ) ;
--CREATE INDEX IX_GDR_HIST_SAMPLESHOT_NI02 ON GDR_HIST_SAMPLESHOT ( SQL_ID ) ;

