DROP TABLE GDR_HIST_COLORED_SQL;
CREATE TABLE GDR_HIST_COLORED_SQL
(
SQL_ID				NUMBER,
CREATE_TIME			DATE,
CON_ID				NUMBER
)
--TABLESPACE VOL_TS
;

DROP INDEX IX_GDR_HIST_COLORED_SQL_NI01;
DROP INDEX IX_GDR_HIST_COLORED_SQL_NI02;

CREATE UNIQUE INDEX IX_GDR_HIST_COLORED_SQL_NI01 ON GDR_HIST_COLORED_SQL ( SQL_ID ) ;
--CREATE INDEX IX_GDR_HIST_COLORED_SQL_NI02 ON GDR_HIST_COLORED_SQL ( SQL_ID ) ;

-- VOL_TS
CREATE UNIQUE INDEX IX_GDR_HIST_COLORED_SQL_NI01 ON GDR_HIST_COLORED_SQL ( SQL_ID ) ;
--CREATE INDEX IX_GDR_HIST_COLORED_SQL_NI02 ON GDR_HIST_COLORED_SQL ( SQL_ID ) ;

