DROP TABLE GDR_HIST_SQL_PLAN;
CREATE TABLE GDR_HIST_SQL_PLAN
(
USER_NAME			VARCHAR(40),
PLAN_HASH_VALUE		NUMBER, 
SQL_ID				NUMBER,
--SQL_ID_SHORT		NUMBER,
SQL_CHILD_NUMBER	NUMBER default 0, 
/*
--ID				NUMBER, 
OPERATION			VARCHAR2(30), 
OPTIONS				VARCHAR2(30), 
OBJECT_NODE			VARCHAR2(128), 
OBJECT#				NUMBER, 
OBJECT_OWNER		VARCHAR2(128), 
OBJECT_NAME			VARCHAR2(128), 
OBJECT_ALIAS		VARCHAR2(261), 
OBJECT_TYPE			VARCHAR2(20), 
OPTIMIZER			VARCHAR2(20), 
PARENT_ID			NUMBER, 
DEPTH				NUMBER, 
POSITION			NUMBER, 
SEARCH_COLUMNS		NUMBER, 
COST				NUMBER, 
CARDINALITY			NUMBER, 
BYTES				NUMBER, 
OTHER_TAG			VARCHAR2(35), 
PARTITION_START		VARCHAR2(64), 
PARTITION_STOP		VARCHAR2(64), 
PARTITION_ID		NUMBER, 
OTHER				VARCHAR2(4000), 
DISTRIBUTION		VARCHAR2(20), 
CPU_COST			NUMBER, 
IO_COST				NUMBER, 
TEMP_SPACE			NUMBER, 
ACCESS_PREDICATES	VARCHAR2(4000), 
FILTER_PREDICATES	VARCHAR2(4000), 
PROJECTION			VARCHAR2(4000), 
TIME				NUMBER, 
QBLOCK_NAME			VARCHAR2(128), 
REMARKS				VARCHAR2(4000), 
TIMESTAMP			DATE, 
OTHER_XML			CLOB, 
CON_DBID			NUMBER, 
CON_ID				NUMBER 
*/
FIRST_SQL_CACHE_TEXT_ID	VARCHAR(64),
FIRST_SESSION_ID	NUMBER,
FIRST_STMT_ID		NUMBER,
FIRST_MODULE		VARCHAR2(48),
FIRST_MACHINE		VARCHAR2(64),
FIRST_PORT			NUMBER,
FIRST_SPID			NUMBER,
SQL_TEXT			VARCHAR(32000),
SQL_TEXT2           VARCHAR(32000),
PlAN_TEXT       	VARCHAR(32000),
PlAN_TEXT2      	VARCHAR(32000),
XLOG_NAME			VARCHAR(128),
XLOG_NAME_KO		VARCHAR(128),
CREATED				DATE DEFAULT SYSDATE,
COMMENT				VARCHAR(1000)
)
--TABLESPACE VOL_TS
;

--ALTER TABLE GDR_HIST_SQL_PLAN ADD COLUMN ( XLOG_NAME VARCHAR(128) );
--UPDATE GDR_HIST_SQL_PLAN SET XLOG_NAME = GDR_SF_XLOG_NAME( SQL_TEXT, SQL_TEXT2 ), XLOG_NAME_KO = GDR_SF_XLOG_NAME( SQL_TEXT, SQL_TEXT2, 'KO' ) WHERE XLOG_NAME IS NULL AND GDR_SF_XLOG_NAME( SQL_TEXT, SQL_TEXT2 ) IS NOT NULL;

DROP INDEX IX_GDR_HIST_SQL_PLAN_NI01;
DROP INDEX IX_GDR_HIST_SQL_PLAN_NI02;
DROP INDEX IX_GDR_HIST_SQL_PLAN_NI03;
DROP INDEX IX_GDR_HIST_SQL_PLAN_NI04;
DROP INDEX IX_GDR_HIST_SQL_PLAN_NI05;

--CREATE UNIQUE INDEX IX_GDR_HIST_SQL_PLAN_NI01 ON GDR_HIST_SQL_PLAN ( PLAN_HASH_VALUE, SQL_ID, USER_NAME ) ;
CREATE UNIQUE INDEX IX_GDR_HIST_SQL_PLAN_NI01 ON GDR_HIST_SQL_PLAN ( PLAN_HASH_VALUE, SQL_ID, CREATED ) ;

CREATE INDEX IX_GDR_HIST_SQL_PLAN_NI02 ON GDR_HIST_SQL_PLAN ( SQL_ID ) ;

--CREATE INDEX IX_GDR_HIST_SQL_PLAN_NI03 ON GDR_HIST_SQL_PLAN ( FIRST_SESSION_ID, FIRST_STMT_ID, CREATED ) ;
CREATE INDEX IX_GDR_HIST_SQL_PLAN_NI03 ON GDR_HIST_SQL_PLAN ( CREATED ) ;

CREATE INDEX IX_GDR_HIST_SQL_PLAN_NI04 ON GDR_HIST_SQL_PLAN ( FIRST_SQL_CACHE_TEXT_ID, CREATED ) ;
CREATE INDEX IX_GDR_HIST_SQL_PLAN_NI05 ON GDR_HIST_SQL_PLAN ( XLOG_NAME ) ;

