DROP SEQUENCE GDR_SQ_SNAP_ID;
DROP SEQUENCE GDR_SQ_SAMPLE_ID;

CREATE SEQUENCE GDR_SQ_SNAP_ID;
CREATE SEQUENCE GDR_SQ_SAMPLE_ID;

ALTER SEQUENCE GDR_SQ_SAMPLE_ID NOCACHE;
ALTER SEQUENCE GDR_SQ_SNAP_ID  NOCACHE;

