--SET.sql
--call DBMS_SESSION.SET_IDENTIFIER( 'OKT_XP1' ) ;

--GET.sql
--SELECT SQL_ID||'/'||SQL_CHILD_NUMBER FROM V$SESSION WHERE CLIENT_IDENTIFIER = 'OKT_XP1' AND STATUS IN ( 'ACTIVE', 'RUNNING' )  ;
SELECT A.SQL_ID||'/'||A.CHILD_NUMBER KEY
     --, A.*
  FROM V$SQL A
       INNER JOIN V$SESSION B ON A.SQL_ID = B.SQL_ID AND B.STATUS IN ( 'ACTIVE', 'RUNNING' ) 
 WHERE 1 = 1
   AND A.SQL_TEXT LIKE '%xx%'
;

