WITH W1 AS
(
SELECT 
       SQL_ID
     , PLAN_HASH_VALUE
     , EXECUTIONS
     , ROUND(ELAPSED_TIME/EXECUTIONS, 0) ELAPSED_TIME
     , ROUND(CPU_TIME/EXECUTIONS, 0) CPU_TIME
  FROM 
       --V$SQL
       OKT_SQL
 WHERE 1=1
   AND EXECUTIONS != 0

)
SELECT SQL_ID
     , COUNT(*) CNT
     , COUNT(DISTINCT PLAN_HASH_VALUE) DCNT
     , SUM(EXECUTIONS) CALLS
     , ROUND( MAX(ELAPSED_TIME)/1000000, 3 ) TMAX
     , ROUND( MIN(ELAPSED_TIME)/1000000, 3 ) TMIN
     , ROUND( AVG(ELAPSED_TIME)/1000000, 3 ) TAVG
     , ROUND( (MAX(ELAPSED_TIME) - MIN(ELAPSED_TIME))/1000000, 3 ) DIFF
     --, ROUND( (MAX(ELAPSED_TIME) - AVG(ELAPSED_TIME))/1000000, 3 ) DIFF2
     , ROUND( STDDEV(ELAPSED_TIME)/AVG(ELAPSED_TIME), 3) STDDEV
  FROM W1
 GROUP BY SQL_ID
HAVING COUNT(DISTINCT PLAN_HASH_VALUE) > 1 
 ORDER BY MAX(ELAPSED_TIME) - MIN(ELAPSED_TIME) DESC
;
