--SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR() );
--SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR( FORMAT => 'ALLSTATS LAST ALL' ) );
--SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'IOSTATS LAST') );
SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST') );

