wget https://oracle-base.com/dba/monitoring/access.sql
wget https://oracle-base.com/dba/monitoring/active_sessions.sql
wget https://oracle-base.com/dba/monitoring/active_user_sessions.sql
wget https://oracle-base.com/dba/monitoring/cache_hit_ratio.sql
wget https://oracle-base.com/dba/monitoring/call_stack.sql
wget https://oracle-base.com/dba/monitoring/code_dep.sql
wget https://oracle-base.com/dba/monitoring/code_dep_distinct.sql
wget https://oracle-base.com/dba/monitoring/code_dep_on.sql
wget https://oracle-base.com/dba/monitoring/code_dep_tree.sql
wget https://oracle-base.com/dba/monitoring/column_defaults.sql
wget https://oracle-base.com/dba/monitoring/controlfiles.sql
wget https://oracle-base.com/dba/monitoring/datafiles.sql
wget https://oracle-base.com/dba/monitoring/db_cache_advice.sql
wget https://oracle-base.com/dba/monitoring/db_info.sql
wget https://oracle-base.com/dba/monitoring/db_links.sql
wget https://oracle-base.com/dba/monitoring/db_links_open.sql
wget https://oracle-base.com/dba/monitoring/db_properties.sql
wget https://oracle-base.com/dba/monitoring/default_tablespaces.sql
wget https://oracle-base.com/dba/monitoring/df_free_space.sql
wget https://oracle-base.com/dba/monitoring/directories.sql
wget https://oracle-base.com/dba/monitoring/directory_permissions.sql
wget https://oracle-base.com/dba/monitoring/dispatchers.sql
wget https://oracle-base.com/dba/monitoring/error_stack.sql
wget https://oracle-base.com/dba/monitoring/errors.sql
wget https://oracle-base.com/dba/monitoring/explain.sql
wget https://oracle-base.com/dba/monitoring/file_io.sql
wget https://oracle-base.com/dba/monitoring/fk_columns.sql
wget https://oracle-base.com/dba/monitoring/fks.sql
wget https://oracle-base.com/dba/monitoring/free_space.sql
wget https://oracle-base.com/dba/monitoring/health.sql
wget https://oracle-base.com/dba/monitoring/hidden_parameters.sql
wget https://oracle-base.com/dba/monitoring/min_datafile_size.sql
wget https://oracle-base.com/dba/monitoring/monitor.sql
wget https://oracle-base.com/dba/monitoring/monitor_memory.sql
wget https://oracle-base.com/dba/monitoring/monitoring_status.sql
wget https://oracle-base.com/dba/monitoring/nls_params.sql
wget https://oracle-base.com/dba/monitoring/non_indexed_fks.sql
wget https://oracle-base.com/dba/monitoring/obj_lock.sql
wget https://oracle-base.com/dba/monitoring/object_privs.sql
wget https://oracle-base.com/dba/monitoring/object_status.sql
wget https://oracle-base.com/dba/monitoring/objects.sql
wget https://oracle-base.com/dba/monitoring/open_cursors.sql
wget https://oracle-base.com/dba/monitoring/open_cursors_by_sid.sql
wget https://oracle-base.com/dba/monitoring/open_cursors_full_by_sid.sql
wget https://oracle-base.com/dba/monitoring/options.sql
wget https://oracle-base.com/dba/monitoring/param_valid_values.sql
wget https://oracle-base.com/dba/monitoring/parameter_diffs.sql
wget https://oracle-base.com/dba/monitoring/parameters.sql
wget https://oracle-base.com/dba/monitoring/parameters_non_default.sql
wget https://oracle-base.com/dba/monitoring/part_tables.sql
wget https://oracle-base.com/dba/monitoring/pga_target_advice.sql
wget https://oracle-base.com/dba/monitoring/pipes.sql
wget https://oracle-base.com/dba/monitoring/profiler_run_details.sql
wget https://oracle-base.com/dba/monitoring/profiler_runs.sql
wget https://oracle-base.com/dba/monitoring/profiles.sql
wget https://oracle-base.com/dba/monitoring/rbs_extents.sql
wget https://oracle-base.com/dba/monitoring/rbs_stats.sql
wget https://oracle-base.com/dba/monitoring/recovery_status.sql
wget https://oracle-base.com/dba/monitoring/recyclebin.sql
wget https://oracle-base.com/dba/monitoring/redo_by_day.sql
wget https://oracle-base.com/dba/monitoring/redo_by_hour.sql
wget https://oracle-base.com/dba/monitoring/redo_by_min.sql
wget https://oracle-base.com/dba/monitoring/source.sql
wget https://oracle-base.com/dba/monitoring/spfile_parameters.sql
wget https://oracle-base.com/dba/monitoring/sql_area.sql
wget https://oracle-base.com/dba/monitoring/sql_text.sql
wget https://oracle-base.com/dba/monitoring/sql_text_by_sid.sql
wget https://oracle-base.com/dba/monitoring/statistics_prefs.sql
wget https://oracle-base.com/dba/monitoring/synonyms_to_missing_objects.sql
wget https://oracle-base.com/dba/monitoring/system_events.sql
wget https://oracle-base.com/dba/monitoring/system_parameters.sql
wget https://oracle-base.com/dba/monitoring/system_privs.sql
wget https://oracle-base.com/dba/monitoring/system_stats.sql
wget https://oracle-base.com/dba/monitoring/table_dep.sql
wget https://oracle-base.com/dba/monitoring/table_extents.sql
wget https://oracle-base.com/dba/monitoring/table_growth.sql
wget https://oracle-base.com/dba/monitoring/table_indexes.sql
wget https://oracle-base.com/dba/monitoring/table_partitions.sql
wget https://oracle-base.com/dba/monitoring/table_stats.sql
wget https://oracle-base.com/dba/monitoring/table_triggers.sql
wget https://oracle-base.com/dba/monitoring/tables_with_locked_stats.sql
wget https://oracle-base.com/dba/monitoring/tables_with_zero_rows.sql
wget https://oracle-base.com/dba/monitoring/tablespaces.sql
wget https://oracle-base.com/dba/monitoring/temp_extent_map.sql
wget https://oracle-base.com/dba/monitoring/temp_free_space.sql
wget https://oracle-base.com/dba/monitoring/temp_io.sql
wget https://oracle-base.com/dba/monitoring/temp_segments.sql
wget https://oracle-base.com/dba/monitoring/temp_usage.sql
wget https://oracle-base.com/dba/monitoring/tempfiles.sql
wget https://oracle-base.com/dba/monitoring/tempseg_usage.sql
wget https://oracle-base.com/dba/monitoring/top_latches.sql
wget https://oracle-base.com/dba/monitoring/top_sessions.sql
wget https://oracle-base.com/dba/monitoring/top_sql.sql
wget https://oracle-base.com/dba/monitoring/high_water_mark.sql
wget https://oracle-base.com/dba/monitoring/hot_blocks.sql
wget https://oracle-base.com/dba/monitoring/identify_trace_file.sql
wget https://oracle-base.com/dba/monitoring/index_extents.sql
wget https://oracle-base.com/dba/monitoring/index_monitoring_status.sql
wget https://oracle-base.com/dba/monitoring/index_partitions.sql
wget https://oracle-base.com/dba/monitoring/index_usage.sql
wget https://oracle-base.com/dba/monitoring/invalid_objects.sql
wget https://oracle-base.com/dba/monitoring/jobs.sql
wget https://oracle-base.com/dba/monitoring/jobs_running.sql
wget https://oracle-base.com/dba/monitoring/large_lob_segments.sql
wget https://oracle-base.com/dba/monitoring/large_segments.sql
wget https://oracle-base.com/dba/monitoring/latch_hit_ratios.sql
wget https://oracle-base.com/dba/monitoring/latch_holders.sql
wget https://oracle-base.com/dba/monitoring/latches.sql
wget https://oracle-base.com/dba/monitoring/library_cache.sql
wget https://oracle-base.com/dba/monitoring/license.sql
wget https://oracle-base.com/dba/monitoring/locked_objects.sql
wget https://oracle-base.com/dba/monitoring/locked_objects_internal.sql
wget https://oracle-base.com/dba/monitoring/logfiles.sql
wget https://oracle-base.com/dba/monitoring/longops.sql
wget https://oracle-base.com/dba/monitoring/lru_latch_ratio.sql
wget https://oracle-base.com/dba/monitoring/max_extents.sql
wget https://oracle-base.com/dba/monitoring/registry_history.sql
wget https://oracle-base.com/dba/monitoring/role_privs.sql
wget https://oracle-base.com/dba/monitoring/roles.sql
wget https://oracle-base.com/dba/monitoring/search_source.sql
wget https://oracle-base.com/dba/monitoring/segment_size.sql
wget https://oracle-base.com/dba/monitoring/segment_stats.sql
wget https://oracle-base.com/dba/monitoring/segments_in_ts.sql
wget https://oracle-base.com/dba/monitoring/session_events.sql
wget https://oracle-base.com/dba/monitoring/session_events_by_sid.sql
wget https://oracle-base.com/dba/monitoring/session_events_by_spid.sql
wget https://oracle-base.com/dba/monitoring/session_io.sql
wget https://oracle-base.com/dba/monitoring/session_pga.sql
wget https://oracle-base.com/dba/monitoring/session_rollback.sql
wget https://oracle-base.com/dba/monitoring/session_stats.sql
wget https://oracle-base.com/dba/monitoring/session_stats_by_sid.sql
wget https://oracle-base.com/dba/monitoring/session_undo.sql
wget https://oracle-base.com/dba/monitoring/session_waits.sql
wget https://oracle-base.com/dba/monitoring/sessions.sql
wget https://oracle-base.com/dba/monitoring/sessions_by_machine.sql
wget https://oracle-base.com/dba/monitoring/sessions_by_sid.sql
wget https://oracle-base.com/dba/monitoring/show_indexes.sql
wget https://oracle-base.com/dba/monitoring/show_space.sql
wget https://oracle-base.com/dba/monitoring/show_tables.sql
wget https://oracle-base.com/dba/monitoring/trace_run_details.sql
wget https://oracle-base.com/dba/monitoring/trace_runs.sql
wget https://oracle-base.com/dba/monitoring/ts_datafiles.sql
wget https://oracle-base.com/dba/monitoring/ts_extent_map.sql
wget https://oracle-base.com/dba/monitoring/ts_free_space.sql
wget https://oracle-base.com/dba/monitoring/ts_full.sql
wget https://oracle-base.com/dba/monitoring/ts_thresholds.sql
wget https://oracle-base.com/dba/monitoring/ts_thresholds_reset.sql
wget https://oracle-base.com/dba/monitoring/ts_thresholds_set_default.sql
wget https://oracle-base.com/dba/monitoring/tuning.sql
wget https://oracle-base.com/dba/monitoring/unusable_indexes.sql
wget https://oracle-base.com/dba/monitoring/unused_space.sql
wget https://oracle-base.com/dba/monitoring/user_hit_ratio.sql
wget https://oracle-base.com/dba/monitoring/user_objects.sql
wget https://oracle-base.com/dba/monitoring/user_roles.sql
wget https://oracle-base.com/dba/monitoring/user_sessions.sql
wget https://oracle-base.com/dba/monitoring/user_system_privs.sql
wget https://oracle-base.com/dba/monitoring/user_temp_space.sql
wget https://oracle-base.com/dba/monitoring/user_undo_space.sql
wget https://oracle-base.com/dba/monitoring/users.sql
wget https://oracle-base.com/dba/monitoring/users_with_role.sql
wget https://oracle-base.com/dba/monitoring/users_with_sys_priv.sql
wget https://oracle-base.com/dba/monitoring/active_session_waits.sql
wget https://oracle-base.com/dba/monitoring/ash.sql
wget https://oracle-base.com/dba/monitoring/datapump_jobs.sql
wget https://oracle-base.com/dba/monitoring/db_usage_hwm.sql
wget https://oracle-base.com/dba/monitoring/dynamic_memory.sql
wget https://oracle-base.com/dba/monitoring/event_histogram.sql
wget https://oracle-base.com/dba/monitoring/feature_usage.sql
wget https://oracle-base.com/dba/monitoring/flashback_db_info.sql
wget https://oracle-base.com/dba/monitoring/generate_multiple_awr_reports.sql
wget https://oracle-base.com/dba/monitoring/job_chain_rules.sql
wget https://oracle-base.com/dba/monitoring/job_chain_steps.sql
wget https://oracle-base.com/dba/monitoring/job_chains.sql
wget https://oracle-base.com/dba/monitoring/job_classes.sql
wget https://oracle-base.com/dba/monitoring/job_programs.sql
wget https://oracle-base.com/dba/monitoring/job_running_chains.sql
wget https://oracle-base.com/dba/monitoring/job_schedules.sql
wget https://oracle-base.com/dba/monitoring/jobs.sql
wget https://oracle-base.com/dba/monitoring/jobs_running.sql
wget https://oracle-base.com/dba/monitoring/lock_tree.sql
wget https://oracle-base.com/dba/monitoring/scheduler_attributes.sql
wget https://oracle-base.com/dba/monitoring/segment_advisor.sql
wget https://oracle-base.com/dba/monitoring/services.sql
wget https://oracle-base.com/dba/monitoring/session_waits.sql
wget https://oracle-base.com/dba/monitoring/sga_buffers.sql
wget https://oracle-base.com/dba/monitoring/sga_dynamic_components.sql
wget https://oracle-base.com/dba/monitoring/sga_dynamic_free_memory.sql
wget https://oracle-base.com/dba/monitoring/sga_resize_ops.sql
wget https://oracle-base.com/dba/monitoring/sysaux_occupants.sql
wget https://oracle-base.com/dba/monitoring/test_calendar_string.sql
wget https://oracle-base.com/dba/monitoring/window_groups.sql
wget https://oracle-base.com/dba/monitoring/windows.sql
wget https://oracle-base.com/dba/monitoring/admin_privs.sql
wget https://oracle-base.com/dba/monitoring/autotask_change_window_schedules.sql
wget https://oracle-base.com/dba/monitoring/fda_ts.sql
wget https://oracle-base.com/dba/monitoring/identify_trace_file.sql
wget https://oracle-base.com/dba/monitoring/result_cache_objects.sql
wget https://oracle-base.com/dba/monitoring/result_cache_report.sql
wget https://oracle-base.com/dba/monitoring/autotask_job_history.sql
wget https://oracle-base.com/dba/monitoring/autotask_schedule.sql
wget https://oracle-base.com/dba/monitoring/database_block_corruption.sql
wget https://oracle-base.com/dba/monitoring/default_passwords.sql
wget https://oracle-base.com/dba/monitoring/diag_info.sql
wget https://oracle-base.com/dba/monitoring/extended_stats.sql
wget https://oracle-base.com/dba/monitoring/fda.sql
wget https://oracle-base.com/dba/monitoring/fda_tables.sql
wget https://oracle-base.com/dba/monitoring/job_credentials.sql
wget https://oracle-base.com/dba/monitoring/job_output_file.sql
wget https://oracle-base.com/dba/monitoring/job_run_details.sql
wget https://oracle-base.com/dba/monitoring/memory_dynamic_components.sql
wget https://oracle-base.com/dba/monitoring/memory_resize_ops.sql
wget https://oracle-base.com/dba/monitoring/memory_target_advice.sql
wget https://oracle-base.com/dba/monitoring/network_acl_privileges.sql
wget https://oracle-base.com/dba/monitoring/network_acls.sql
wget https://oracle-base.com/dba/monitoring/result_cache_statistics.sql
wget https://oracle-base.com/dba/monitoring/result_cache_status.sql
wget https://oracle-base.com/dba/monitoring/session_fix.sql
wget https://oracle-base.com/dba/monitoring/statistics_global_prefs.sql
wget https://oracle-base.com/dba/monitoring/system_fix.sql
wget https://oracle-base.com/dba/monitoring/system_fix_count.sql
wget https://oracle-base.com/dba/monitoring/temp_free_space.sql
wget https://oracle-base.com/dba/monitoring/cdb_resource_plan_directives.sql
wget https://oracle-base.com/dba/monitoring/cdb_resource_plans.sql
wget https://oracle-base.com/dba/monitoring/cdb_resource_profile_directives.sql
wget https://oracle-base.com/dba/monitoring/credentials.sql
wget https://oracle-base.com/dba/monitoring/host_aces.sql
wget https://oracle-base.com/dba/monitoring/host_acls.sql
wget https://oracle-base.com/dba/monitoring/lockdown_profiles.sql
wget https://oracle-base.com/dba/monitoring/login.sql
wget https://oracle-base.com/dba/monitoring/pdbs.sql
wget https://oracle-base.com/dba/monitoring/plugin_violations.sql
wget https://oracle-base.com/dba/monitoring/priv_captures.sql
wget https://oracle-base.com/dba/monitoring/redaction_columns.sql
wget https://oracle-base.com/dba/monitoring/redaction_policies.sql
wget https://oracle-base.com/dba/monitoring/redaction_value_defaults.sql
wget https://oracle-base.com/dba/monitoring/services.sql
wget https://oracle-base.com/dba/monitoring/lockdown_rules.sql
wget https://oracle-base.com/dba/monitoring/max_pdb_snapshots.sql
wget https://oracle-base.com/dba/monitoring/pdb_snapshot_mode.sql
wget https://oracle-base.com/dba/monitoring/pdb_snapshots.sql
wget https://oracle-base.com/dba/monitoring/auto_index_config.sql auto_indexes.sql
wget https://oracle-base.com/dba/monitoring/disable_chk.sql
wget https://oracle-base.com/dba/monitoring/disable_fk.sql
wget https://oracle-base.com/dba/monitoring/disable_pk.sql
wget https://oracle-base.com/dba/monitoring/disable_ref_fk.sql
wget https://oracle-base.com/dba/monitoring/enable_chk.sql
wget https://oracle-base.com/dba/monitoring/enable_fk.sql
wget https://oracle-base.com/dba/monitoring/enable_pk.sql
wget https://oracle-base.com/dba/monitoring/enable_ref_fk.sql
wget https://oracle-base.com/dba/monitoring/analyze_all.sql
wget https://oracle-base.com/dba/monitoring/base64decode.sql
wget https://oracle-base.com/dba/monitoring/base64encode.sql
wget https://oracle-base.com/dba/monitoring/blob_to_clob.sql
wget https://oracle-base.com/dba/monitoring/blob_to_file.sql
wget https://oracle-base.com/dba/monitoring/clob_to_blob.sql
wget https://oracle-base.com/dba/monitoring/clob_to_file.sql
wget https://oracle-base.com/dba/monitoring/column_comments.sql
wget https://oracle-base.com/dba/monitoring/comments.sql
wget https://oracle-base.com/dba/monitoring/compile_all.sql
wget https://oracle-base.com/dba/monitoring/compile_all_bodies.sql
wget https://oracle-base.com/dba/monitoring/compile_all_funcs.sql
wget https://oracle-base.com/dba/monitoring/csv.sql
wget https://oracle-base.com/dba/monitoring/date_api.sql
wget https://oracle-base.com/dba/monitoring/dict_comments.sql
wget https://oracle-base.com/dba/monitoring/digest_auth_api.sql
wget https://oracle-base.com/dba/monitoring/drop_all.sql
wget https://oracle-base.com/dba/monitoring/file_to_blob.sql
wget https://oracle-base.com/dba/monitoring/file_to_clob.sql
wget https://oracle-base.com/dba/monitoring/find_object.sql
wget https://oracle-base.com/dba/monitoring/login.sql
wget https://oracle-base.com/dba/monitoring/part_hv_to_date.sql
wget https://oracle-base.com/dba/monitoring/proc_defs.sql
wget https://oracle-base.com/dba/monitoring/rebuild_index.sql
wget https://oracle-base.com/dba/monitoring/smart_quotes_api.sql
wget https://oracle-base.com/dba/monitoring/soap_api.sql
wget https://oracle-base.com/dba/monitoring/string_agg.sql
wget https://oracle-base.com/dba/monitoring/string_api.sql
wget https://oracle-base.com/dba/monitoring/switch_schema.sql
wget https://oracle-base.com/dba/monitoring/table_comments.sql
wget https://oracle-base.com/dba/monitoring/table_defs.sql
wget https://oracle-base.com/dba/monitoring/table_differences.sql
wget https://oracle-base.com/dba/monitoring/compile_all_procs.sql
wget https://oracle-base.com/dba/monitoring/compile_all_specs.sql
wget https://oracle-base.com/dba/monitoring/compile_all_trigs.sql
wget https://oracle-base.com/dba/monitoring/compile_all_views.sql
wget https://oracle-base.com/dba/monitoring/conversion_api.sql
wget https://oracle-base.com/dba/monitoring/gen_health.sql
wget https://oracle-base.com/dba/monitoring/get_pivot.sql
wget https://oracle-base.com/dba/monitoring/get_stat.sql
wget https://oracle-base.com/dba/monitoring/ts_move_api.sql
wget https://oracle-base.com/dba/monitoring/locked_objects_rac.sql
wget https://oracle-base.com/dba/monitoring/longops_rac.sql
wget https://oracle-base.com/dba/monitoring/monitor_memory_rac.sql
wget https://oracle-base.com/dba/monitoring/session_undo_rac.sql
wget https://oracle-base.com/dba/monitoring/session_waits_rac.sql
wget https://oracle-base.com/dba/monitoring/sessions_rac.sql
wget https://oracle-base.com/dba/monitoring/active_plan.sql
wget https://oracle-base.com/dba/monitoring/consumer_group_usage.sql
wget https://oracle-base.com/dba/monitoring/consumer_groups.sql
wget https://oracle-base.com/dba/monitoring/plan_directives.sql
wget https://oracle-base.com/dba/monitoring/resource_plans.sql
wget https://oracle-base.com/dba/monitoring/backup.sql
wget https://oracle-base.com/dba/monitoring/build_api.sql
wget https://oracle-base.com/dba/monitoring/build_api2.sql
wget https://oracle-base.com/dba/monitoring/create_data.sql
wget https://oracle-base.com/dba/monitoring/db_link_ddl.sql
wget https://oracle-base.com/dba/monitoring/directory_ddl.sql
wget https://oracle-base.com/dba/monitoring/drop_cons_on_table.sql
wget https://oracle-base.com/dba/monitoring/drop_fks_on_table.sql
wget https://oracle-base.com/dba/monitoring/drop_fks_ref_table.sql
wget https://oracle-base.com/dba/monitoring/drop_indexes.sql
wget https://oracle-base.com/dba/monitoring/fks_on_table_ddl.sql
wget https://oracle-base.com/dba/monitoring/fks_ref_table_ddl.sql
wget https://oracle-base.com/dba/monitoring/index_monitoring_off.sql
wget https://oracle-base.com/dba/monitoring/index_monitoring_on.sql
wget https://oracle-base.com/dba/monitoring/job_ddl.sql
wget https://oracle-base.com/dba/monitoring/logon_as_user.sql
wget https://oracle-base.com/dba/monitoring/logon_as_user_orig.sql
wget https://oracle-base.com/dba/monitoring/monitoring_off.sql
wget https://oracle-base.com/dba/monitoring/monitoring_on.sql
wget https://oracle-base.com/dba/monitoring/network_acls_ddl.sql
wget https://oracle-base.com/dba/monitoring/object_grants.sql
wget https://oracle-base.com/dba/monitoring/profile_ddl.sql
wget https://oracle-base.com/dba/monitoring/rbs_structure.sql
wget https://oracle-base.com/dba/monitoring/recreate_table.sql
wget https://oracle-base.com/dba/monitoring/role_ddl.sql
wget https://oracle-base.com/dba/monitoring/sequence_ddl.sql
wget https://oracle-base.com/dba/monitoring/synonym_by_object_owner_ddl.sql
wget https://oracle-base.com/dba/monitoring/synonym_ddl.sql
wget https://oracle-base.com/dba/monitoring/synonym_public_remote_ddl.sql
wget https://oracle-base.com/dba/monitoring/table_constraints_ddl.sql
wget https://oracle-base.com/dba/monitoring/table_ddl.sql
wget https://oracle-base.com/dba/monitoring/table_grants_ddl.sql
wget https://oracle-base.com/dba/monitoring/table_indexes_ddl.sql
wget https://oracle-base.com/dba/monitoring/table_triggers_ddl.sql
wget https://oracle-base.com/dba/monitoring/tablespace_ddl.sql
wget https://oracle-base.com/dba/monitoring/tablespace_structure.sql
wget https://oracle-base.com/dba/monitoring/trigger_ddl.sql
wget https://oracle-base.com/dba/monitoring/user_ddl.sql
wget https://oracle-base.com/dba/monitoring/view_ddl.sql
wget https://oracle-base.com/dba/monitoring/grant_delete.sql
wget https://oracle-base.com/dba/monitoring/grant_execute.sql
wget https://oracle-base.com/dba/monitoring/grant_insert.sql
wget https://oracle-base.com/dba/monitoring/grant_select.sql
wget https://oracle-base.com/dba/monitoring/grant_update.sql
wget https://oracle-base.com/dba/monitoring/package_synonyms.sql
wget https://oracle-base.com/dba/monitoring/schema_write_access.sql
wget https://oracle-base.com/dba/monitoring/sequence_synonyms.sql
wget https://oracle-base.com/dba/monitoring/table_synonyms.sql
wget https://oracle-base.com/dba/monitoring/view_synonyms.sql
