CREATE OR REPLACE FUNCTION US_GDMON.DATE2UX
(
    A_TIMESTAMP     IN  DATE
,   A_SCALE         IN  NUMBER  DEFAULT NULL
)
RETURN NUMBER(13)
IS
    V_UNIX_TS       NUMBER(13);
BEGIN
    IF A_SCALE IS NULL THEN
        V_UNIX_TS := ( A_TIMESTAMP - TO_DATE('1970010109','YYYYMMDDHH24') ) * 60 * 60 * 24 ;
    ELSE
        V_UNIX_TS := ( A_TIMESTAMP - TO_DATE('1970010109','YYYYMMDDHH24') ) * 60 * 60 * 24 * 1000 + TO_NUMBER( TO_CHAR( A_TIMESTAMP, 'FF3' ) ) ;
    END IF;

    RETURN V_UNIX_TS;
EXCEPTION
    WHEN OTHERS THEN
        SYSTEM_.PRINTLN('['||TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS.FF6')||'] ERR-'||SQLCODE||' '||SQLERRM );
        RAISE;
        --RETURN V_UNIX_TS ;
END;
/

GRANT EXECUTE ON US_GDMON.DATE2UX TO PUBLIC;


CREATE PUBLIC SYNONYM DATE2UX FOR US_GDMON.DATE2UX;
