CREATE OR REPLACE VIEW US_GDMON.GD_ALL_OBJECTS AS
SELECT U.USER_NAME OWNER
     , T.TABLE_NAME OBJECT_NAME
     , DECODE( TABLE_TYPE,'T','TABLE','V','VIEW','S','SEQUENCE','UNKNOWN-'||TABLE_TYPE ) OBJECT_TYPE
     , CAST( 'VALID' AS VARCHAR(10)) STATUS
     , T.CREATED, T.LAST_DDL_TIME
     , CAST(NULL AS VARCHAR(250)) JUSEOK
  FROM SYSTEM_.SYS_TABLES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.INDEX_NAME
     , 'INDEX'    
     , 'VALID'
     , T.CREATED, T.LAST_DDL_TIME
     , NULL
  FROM SYSTEM_.SYS_INDICES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.PROC_NAME
     , DECODE(OBJECT_TYPE,0,'PROCEDURE',1,'FUNCTION',3,'TYPE','UNKNOWN-'||OBJECT_TYPE)
     , DECODE(STATUS,0,'VALID','INVALID')
     , T.CREATED, T.LAST_DDL_TIME
     , NULL
  FROM SYSTEM_.SYS_PROCEDURES_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT U.USER_NAME
     , T.TRIGGER_NAME
     , 'TRIGGER'    
     , DECODE(IS_ENABLE,1,'VALID','INVALID')
     , T.CREATED, T.LAST_DDL_TIME
     , NULL
  FROM SYSTEM_.SYS_TRIGGERS_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
 UNION ALL 
SELECT NVL(U.USER_NAME, 'PUBLIC')
     , T.SYNONYM_NAME
     , 'SYNONYM'    
     -- [TODO] US_GDMON.ALL_OBJECTS_FOR_VALID 테이블을 매일 주기적으로 갱신필요
     --, NVL( ( SELECT 'VALID' FROM US_GDMON.ALL_OBJECTS_FOR_VALID X WHERE X.OWNER = T.OBJECT_OWNER_NAME AND X.OBJECT_NAME = T.OBJECT_NAME LIMIT 1 ) , 'INVALID' ) STATUS
     , NVL( ( SELECT 'VALID' FROM US_GDMON.ALL_OBJECTS_FOR_VALID X WHERE ( X.OWNER = T.OBJECT_OWNER_NAME AND X.OBJECT_NAME = T.OBJECT_NAME ) OR ( X.OWNER = 'PUBLIC' AND X.OBJECT_NAME = T.OBJECT_NAME AND T.SYNONYM_NAME != T.OBJECT_NAME ) LIMIT 1 ) , 'INVALID' ) STATUS
     , T.CREATED, T.LAST_DDL_TIME
     , '--> '||T.OBJECT_OWNER_NAME||'.'||T.OBJECT_NAME JUSEOK
  FROM SYSTEM_.SYS_SYNONYMS_ T
       LEFT OUTER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.SYNONYM_OWNER_ID
 WHERE 1=1
   AND T.OBJECT_OWNER_NAME NOT IN ('SYSTEM_')
 UNION ALL 
SELECT U.USER_NAME
     , T.CONSTRAINT_NAME
     , 'FOREIGN KEY'    
     , DECODE(VALIDATED,'T','VALIDATED','NOVALIDATED')
     , NULL CREATED, NULL LAST_DDL_TIME
     , NULL
  FROM SYSTEM_.SYS_CONSTRAINTS_ T
       INNER JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = T.USER_ID
 WHERE 1=1
   AND CONSTRAINT_TYPE = 0
;

CREATE PUBLIC SYNONYM ALL_OBJECTS FOR US_GDMON.GD_ALL_OBJECTS;
