CREATE TABLE US_GDMON.GDR_HIST_SQL_PLAN
(
    USER_NAME               VARCHAR(40),
    PLAN_HASH_VALUE         NUMBER(38),
    SQL_ID                  NUMBER(38),
    SQL_CHILD_NUMBER        NUMBER(38),
    FIRST_SQL_CACHE_TEXT_ID VARCHAR(64),
    FIRST_SESSION_ID        NUMBER(38),
    FIRST_STMT_ID           NUMBER(38),
    FIRST_MODULE            VARCHAR(48),
    FIRST_MACHINE           VARCHAR(64),
    FIRST_PORT              NUMBER(38),
    FIRST_SPID              NUMBER(38),
    SQL_TEXT                VARCHAR(32000),
    SQL_TEXT2               VARCHAR(32000),
    PLAN_TEXT               VARCHAR(32000),
    PLAN_TEXT2              VARCHAR(32000),
    COMMENT                 VARCHAR(1000),
    XLOG_NAME               VARCHAR(128),
    XLOG_NAME_KO            VARCHAR(128),
    CREATED                 DATE DEFAULT SYSDATE
)
PCTFREE 5;

CREATE UNIQUE INDEX US_GDMON.IX_GDR_HIST_SQL_PLAN_NI01
ON US_GDMON.GDR_HIST_SQL_PLAN
(PLAN_HASH_VALUE,SQL_ID,CREATED)
;

CREATE INDEX US_GDMON.IX_GDR_HIST_SQL_PLAN_NI02
ON US_GDMON.GDR_HIST_SQL_PLAN
(SQL_ID)
;

CREATE INDEX US_GDMON.IX_GDR_HIST_SQL_PLAN_NI03
ON US_GDMON.GDR_HIST_SQL_PLAN
(CREATED)
;

CREATE INDEX US_GDMON.IX_GDR_HIST_SQL_PLAN_NI04
ON US_GDMON.GDR_HIST_SQL_PLAN
(FIRST_SQL_CACHE_TEXT_ID,CREATED)
;

CREATE INDEX US_GDMON.IX_GDR_HIST_SQL_PLAN_NI05
ON US_GDMON.GDR_HIST_SQL_PLAN
(XLOG_NAME)
;
