
SELECT SYSDATE
     , A.*
     , ROUND(A.TIME_WAITED*100/X.SVAL,2) PCT
  FROM V$SYSTEM_EVENT A
     , (SELECT SUM(TIME_WAITED) SVAL FROM V$SYSTEM_EVENT) X
 ORDER BY A.TOTAL_TIMEOUTS DESC, A.TIME_WAITED DESC
;
